Repository brain-tec/operating-unit, pull requests merged in 2019-04, with the labels that each got.

#1 Syncing from upstream OCA/operating-unit (9.0)
  account_voucher_operating_unit/static/description/icon.png
  purchase_request_operating_unit/static/description/icon.png
  purchase_request_procurement_operating_unit/static/description/icon.png
  purchase_request_to_requisition_operating_unit/static/description/icon.png
  purchase_request_to_rfq_operating_unit/static/description/icon.png
  purchase_requisition_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/icon.png
Labels: 9.0

#2 Syncing from upstream OCA/operating-unit (10.0)
  account_invoice_merge_operating_unit/static/description/icon.png
  account_invoice_qweb_operating_unit/static/description/icon.png
  account_voucher_operating_unit/static/description/icon.png
  mis_builder_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/icon.png
  purchase_request_operating_unit/static/description/icon.png
  purchase_request_procurement_operating_unit/static/description/icon.png
  purchase_request_to_rfq_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/icon.png
  stock_account_operating_unit/static/description/icon.png
  stock_picking_qweb_operating_unit/static/description/icon.png
Labels: 10.0

#3 New module mail_operating_unit to introduce the operating unit to mail.
  mail_operating_unit/README.rst
  mail_operating_unit/__init__.py
  mail_operating_unit/__manifest__.py
  mail_operating_unit/models/__init__.py
  mail_operating_unit/models/mail_alias_ext.py
  mail_operating_unit/models/mail_mail_ext.py
  mail_operating_unit/models/mail_template_ext.py
  mail_operating_unit/models/operating_unit.py
  mail_operating_unit/readme/CONTRIBUTORS.rst
  mail_operating_unit/readme/DESCRIPTION.rst
  mail_operating_unit/readme/ROADMAP.rst
  mail_operating_unit/readme/USAGE.rst
  mail_operating_unit/security/mail_alias_security.xml
  mail_operating_unit/security/mail_template_security.xml
  mail_operating_unit/static/description/icon.png
  mail_operating_unit/static/description/index.html
  mail_operating_unit/views/mail_alias_views_ext.xml
  mail_operating_unit/views/mail_template_views_ext.xml
  mail_operating_unit/views/operating_unit_views_ext.xml
  mail_operating_unit/wizard/__init__.py
  mail_operating_unit/wizard/mail_compose_message_ext.py
  mail_operating_unit/wizard/mail_compose_message_view_ext.xml
Labels: 12.0.project_mi_465, enhancement
