Repository brain-tec/operating-unit, pull requests merged in 2019-07, with the labels that each got.

#9 [bt#5911] Fix a bug with expected singleton
  hr_expense_operating_unit/models/hr_expense.py
Labels: 12.0.project_mi_465

#10 [bt#6768] Fixes crash when logging a note over an object that doesn't have an operating_unit_id.
  mail_operating_unit/wizard/mail_compose_message_ext.py
Labels: 12.0.project_mi_465

#11 [bt#5910] Access rights to own user partners
  partner_operating_unit/security/res_partner_security.xml
Labels: 12.0.project_mi_465

#12 Syncing from upstream OCA/operating-unit (11.0)
  sale_operating_unit/static/description/index.html
Labels: 11.0

#13 Syncing from upstream OCA/operating-unit (12.0)
  hr_contract_operating_unit/static/description/index.html
  operating_unit/static/description/index.html
  sales_team_operating_unit/static/description/index.html
Labels: 12.0
