Repository brain-tec/operating-unit, pull requests merged in 2019-05, with the labels that each got.

#4 [ADD] New module for adding operating unit concept on stock landed cost
  stock_landed_cost_operating_unit/__init__.py
  stock_landed_cost_operating_unit/__manifest__.py
  stock_landed_cost_operating_unit/model/__init__.py
  stock_landed_cost_operating_unit/model/stock_landed_cost.py
  stock_landed_cost_operating_unit/security/stock_landed_cost_security.xml
  stock_landed_cost_operating_unit/view/stock_landed_cost_views.xml
Labels: 12.0.project_mi_465

#5 [t114195] Safely checks the maybe-existing attribute operating_unit_id.
  mail_operating_unit/models/mail_mail_ext.py
Labels: 12.0.project_mi_465

#6 Syncing from upstream OCA/operating-unit (11.0)
  sale_operating_unit/README.rst
  sale_operating_unit/__init__.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/models/__init__.py
  sale_operating_unit/models/crm_team.py
  sale_operating_unit/models/sale.py
  sale_operating_unit/readme/CONTRIBUTORS.rst
  sale_operating_unit/readme/DESCRIPTION.rst
  sale_operating_unit/readme/USAGE.rst
  sale_operating_unit/report/__init__.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/security/sale_security.xml
  sale_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/index.html
  sale_operating_unit/tests/__init__.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_operating_unit/views/sale_report_view.xml
  sale_operating_unit/views/sale_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_operating_unit/odoo/addons/sale_operating_unit
  setup/sale_operating_unit/setup.cfg
  setup/sale_operating_unit/setup.py
Labels: 11.0

#7 Syncing from upstream OCA/operating-unit (12.0)
  hr_contract_operating_unit/README.rst
  hr_contract_operating_unit/__init__.py
  hr_contract_operating_unit/__manifest__.py
  hr_contract_operating_unit/models/__init__.py
  hr_contract_operating_unit/models/hr_contract.py
  hr_contract_operating_unit/readme/CONTRIBUTORS.rst
  hr_contract_operating_unit/readme/DESCRIPTION.rst
  hr_contract_operating_unit/readme/USAGE.rst
  hr_contract_operating_unit/security/hr_contract_security.xml
  hr_contract_operating_unit/static/description/icon.png
  hr_contract_operating_unit/static/description/index.html
  hr_contract_operating_unit/tests/__init__.py
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  hr_contract_operating_unit/views/hr_contract_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_contract_operating_unit/odoo/addons/hr_contract_operating_unit
  setup/hr_contract_operating_unit/setup.py
Labels: 12.0
