Repository brain-tec/operating-unit, pull requests merged in 2020-09, with the labels that each got.

#125 [t117662] Migrations including customizations from v12
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/tests/test_hr_expense_operating_unit.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/migrations/13.0.1.0.0/pre-migration.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/tests/OperatingUnitsTransactionCase.py
  operating_unit/tests/__init__.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/res_users_view.xml
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
Labels: 13.0.project_mi_465

#126 Syncing from upstream OCA/operating-unit (13.0)
  account_operating_unit/i18n/account_operating_unit.pot
  hr_expense_operating_unit/__manifest__.py
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/tests/test_hr_expense_operating_unit.py
Labels: 13.0

#127 [t116909] Adding default operating unit for existing demo Sales Team
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/demo/sales_team_demo.xml
Labels: 12.0.project_mi_465
