Repository brain-tec/operating-unit, pull requests merged in 2020-05, with the labels that each got.

#106 Syncing from upstream OCA/operating-unit (13.0)
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/readme/CONTRIBUTORS.rst
  mrp_operating_unit/readme/DESCRIPTION.rst
  mrp_operating_unit/readme/USAGE.rst
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mrp_operating_unit/odoo/addons/mrp_operating_unit
  setup/mrp_operating_unit/setup.py
Labels: 13.0

#107 Syncing from upstream OCA/operating-unit (12.0)
  operating_unit/i18n/it.po
Labels: 12.0

#108 Syncing from upstream OCA/operating-unit (13.0)
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/models/account_move.py
  account_operating_unit/views/account_move_view.xml
  account_operating_unit/views/account_payment_view.xml
Labels: 13.0

#109 Updating project branch with 12.0 update_20200512
  operating_unit/i18n/it.po
Labels: 12.0.project_mi_465

#110 Syncing from upstream OCA/operating-unit (13.0)
  .pre-commit-config.yaml
Labels: 13.0

#111 [t116909] Improving error messages for sale_operating_unit
  sale_operating_unit/models/sale_order.py
Labels: 12.0.project_mi_465

#112 [t117247] Fixes the placement of the uninstall_hook so that account_operating_unit can be uninstalled.
  account_operating_unit/__init__.py
  account_operating_unit/models/__init__.py
Labels: 12.0.project_mi_465

#113 [t116909] Improving error messages for sale_operating_unit and respec…
  sale_operating_unit/models/sale_order.py
Labels: 12.0.project_mi_465

#114 Syncing from upstream OCA/operating-unit (13.0)
  account_operating_unit/__manifest__.py
Labels: 13.0
