Repository brain-tec/operating-unit, pull requests merged in 2020-04, with the labels that each got.

#95 Syncing from upstream OCA/operating-unit (12.0)
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/i18n/mis_builder_operating_unit.pot
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_operating_unit/readme/DESCRIPTION.rst
  mis_builder_operating_unit/readme/USAGE.rst
  mis_builder_operating_unit/security/mis_builder_security.xml
  mis_builder_operating_unit/static/description/icon.png
  mis_builder_operating_unit/static/description/index.html
  mis_builder_operating_unit/view/mis_builder.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mis_builder_operating_unit/odoo/addons/mis_builder_operating_unit
  setup/mis_builder_operating_unit/setup.py
Labels: 12.0

#96 Update 20200414 updating submodules
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/i18n/mis_builder_operating_unit.pot
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_operating_unit/readme/DESCRIPTION.rst
  mis_builder_operating_unit/readme/USAGE.rst
  mis_builder_operating_unit/security/mis_builder_security.xml
  mis_builder_operating_unit/static/description/icon.png
  mis_builder_operating_unit/static/description/index.html
  mis_builder_operating_unit/view/mis_builder.xml
  oca_dependencies.txt
  operating_unit/i18n/da.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mis_builder_operating_unit/odoo/addons/mis_builder_operating_unit
  setup/mis_builder_operating_unit/setup.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/i18n/pt.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/models/stock_move.py
  stock_operating_unit/security/stock_security.xml
Labels: 12.0.project_mi_465

#97 Syncing from upstream OCA/operating-unit (13.0)
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/models/__init__.py
  account_operating_unit/models/account_journal.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_payment.py
  account_operating_unit/models/res_company.py
  account_operating_unit/readme/CONFIGURE.rst
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/readme/DESCRIPTION.rst
  account_operating_unit/readme/ROADMAP.rst
  account_operating_unit/readme/USAGE.rst
  account_operating_unit/report/__init__.py
  account_operating_unit/report/account_invoice_report.py
  account_operating_unit/security/account_security.xml
  account_operating_unit/static/description/icon.png
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/__init__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/views/account_invoice_report_view.xml
  account_operating_unit/views/account_journal_view.xml
  account_operating_unit/views/account_move_view.xml
  account_operating_unit/views/account_payment_view.xml
  account_operating_unit/views/company_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_operating_unit/odoo/addons/account_operating_unit
  setup/account_operating_unit/setup.py
Labels: 13.0

#98 Syncing from upstream OCA/operating-unit (12.0)
  mis_builder_operating_unit/i18n/da.po
Labels: 12.0

#99 Syncing from upstream OCA/operating-unit (13.0)
  hr_expense_operating_unit/README.rst
  hr_expense_operating_unit/__init__.py
  hr_expense_operating_unit/__manifest__.py
  hr_expense_operating_unit/i18n/hr_expense_operating_unit.pot
  hr_expense_operating_unit/models/__init__.py
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit/readme/DESCRIPTION.rst
  hr_expense_operating_unit/readme/USAGE.rst
  hr_expense_operating_unit/security/hr_expense_security.xml
  hr_expense_operating_unit/static/description/icon.png
  hr_expense_operating_unit/static/description/index.html
  hr_expense_operating_unit/tests/__init__.py
  hr_expense_operating_unit/tests/test_hr_expense_operating_unit.py
  hr_expense_operating_unit/views/hr_expense_view.xml
  sale_operating_unit/README.rst
  sale_operating_unit/__init__.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/i18n/sale_operating_unit.pot
  sale_operating_unit/models/__init__.py
  sale_operating_unit/models/crm_team.py
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/readme/CONTRIBUTORS.rst
  sale_operating_unit/readme/DESCRIPTION.rst
  sale_operating_unit/readme/USAGE.rst
  sale_operating_unit/report/__init__.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/security/sale_security.xml
  sale_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/index.html
  sale_operating_unit/tests/__init__.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_operating_unit/views/sale_report_view.xml
  sale_operating_unit/views/sale_view.xml
  sale_operating_unit/wizard/__init__.py
  sale_operating_unit/wizard/sale_make_invoice_advance.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_expense_operating_unit/odoo/addons/hr_expense_operating_unit
  setup/hr_expense_operating_unit/setup.py
  setup/sale_operating_unit/odoo/addons/sale_operating_unit
  setup/sale_operating_unit/setup.py
Labels: 13.0

#100 Update 20200421 - Updating from latest 12.0
  mis_builder_operating_unit/i18n/da.po
Labels: 12.0.project_mi_465

#101 Syncing from upstream OCA/operating-unit (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_operating_unit/odoo/addons/stock_operating_unit
  setup/stock_operating_unit/setup.py
  stock_operating_unit/README.rst
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/data/stock_data.xml
  stock_operating_unit/demo/stock_demo.xml
  stock_operating_unit/hooks.py
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/model/__init__.py
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_move.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/readme/CONFIGURE.rst
  stock_operating_unit/readme/CONTRIBUTORS.rst
  stock_operating_unit/readme/DESCRIPTION.rst
  stock_operating_unit/readme/ROADMAP.rst
  stock_operating_unit/readme/USAGE.rst
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/index.html
  stock_operating_unit/tests/__init__.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
  stock_operating_unit/view/stock.xml
Labels: 13.0

#102 Syncing from upstream OCA/operating-unit (12.0)
  product_operating_unit/README.rst
  product_operating_unit/__init__.py
  product_operating_unit/__manifest__.py
  product_operating_unit/i18n/product_operating_unit.pot
  product_operating_unit/models/__init__.py
  product_operating_unit/models/product_category.py
  product_operating_unit/models/product_template.py
  product_operating_unit/readme/CONTRIBUTORS.rst
  product_operating_unit/readme/DESCRIPTION.rst
  product_operating_unit/readme/ROADMAP.rst
  product_operating_unit/readme/USAGE.rst
  product_operating_unit/security/product_template_security.xml
  product_operating_unit/static/description/icon.png
  product_operating_unit/static/description/index.html
  product_operating_unit/tests/__init__.py
  product_operating_unit/tests/test_product_operating_unit.py
  product_operating_unit/views/product_category_view.xml
  product_operating_unit/views/product_template_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_operating_unit/odoo/addons/product_operating_unit
  setup/product_operating_unit/setup.py
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
  stock_operating_unit/tests/test_stock_operating_unit.py
Labels: 12.0
