Repository brain-tec/operating-unit, pull requests merged in 2020-06, with the labels that each got.

#115 Syncing from upstream OCA/operating-unit (12.0)
  operating_unit/i18n/pt.po
Labels: 12.0

#116 Update 2020-06-09: Update 12.0.project_MI_465 from BT/12.0
  operating_unit/i18n/pt.po
Labels: 12.0.project_mi_465

#117 Syncing from upstream OCA/operating-unit (10.0)
  README.md
  stock_operating_unit/__manifest__.py
  stock_operating_unit/security/stock_security.xml
Labels: 10.0
