Repository brain-tec/operating-unit, pull requests merged in 2020-11, with the labels that each got.

#149 Syncing from upstream OCA/operating-unit (13.0)
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: 13.0

#150 Syncing from upstream OCA/operating-unit (14.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
Labels: 14.0

#151 Syncing from upstream OCA/operating-unit (13.0)
  .pre-commit-config.yaml
Labels: 13.0

#153 Automatically formatting the code according to pre-commit
  .braintec/deploy.yaml
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/tests/test_hr_expense_operating_unit.py
  operating_unit/migrations/13.0.1.0.0/pre-migration.py
  operating_unit/models/operating_unit.py
  operating_unit/tests/OperatingUnitsTransactionCase.py
  operating_unit/tests/test_operating_unit.py
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_stock_operating_unit/__manifest__.py
  sale_stock_operating_unit/models/sale_order.py
  sale_stock_operating_unit/models/stock_move.py
  sale_stock_operating_unit/models/stock_warehouse.py
  sale_stock_operating_unit/tests/test_sale_stock_operating_unit.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  stock_account_operating_unit/__manifest__.py
  stock_account_operating_unit/model/stock_move.py
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
  stock_landed_cost_operating_unit/__manifest__.py
  stock_landed_cost_operating_unit/model/__init__.py
  stock_landed_cost_operating_unit/model/stock_landed_cost.py
  stock_landed_cost_operating_unit/security/stock_landed_cost_security.xml
  stock_landed_cost_operating_unit/view/stock_landed_cost_views.xml
Labels: 13.0.project_mi_465

#154 Removing unneeded ext folder
  ext/.gitignore
Labels: 13.0.project_mi_465

#152 Updating from latest 13.0
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: 13.0.project_mi_465

#155 Syncing from upstream OCA/operating-unit (12.0)
  operating_unit/i18n/fr.po
Labels: 12.0

#157 Removing commitor-tags
  .braintec/deploy.yaml
Labels: 12.0.project_mi_465

#156 Update 20201124 - Updating from braintec fork
  operating_unit/i18n/fr.po
Labels: 12.0.project_mi_465

#159 [t113973] Update 20201201: Set commitortag for odoo and enterprise
  .braintec/deploy.yaml
Labels: 13.0.project_mi_465
