Repository brain-tec/operating-unit, pull requests merged in 2020-12, with the labels that each got.

#160 Syncing from upstream OCA/operating-unit (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  .travis.yml
Labels: 14.0

#161 Syncing from upstream OCA/operating-unit (12.0)
  hr_expense_operating_unit/__manifest__.py
  hr_expense_operating_unit/models/hr_expense.py
Labels: 12.0

#162 [t119559] Index the m2o 'Operating Unit' in Sales Order
  sale_operating_unit/__manifest__.py
  sale_operating_unit/models/sale_order.py
Labels: 13.0.project_mi_465
