Repository brain-tec/operating-unit, pull requests merged in 2020-10, with the labels that each got.

#129 Syncing from upstream OCA/operating-unit (13.0)
  purchase_operating_unit/README.rst
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/readme/CONTRIBUTORS.rst
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/tests/test_purchase_operating_unit.py
Labels: 13.0

#130 Syncing from upstream OCA/operating-unit (12.0)
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/demo/sales_team_demo.xml
Labels: 12.0

#132 Updating from latest OCA 13.0
  purchase_operating_unit/README.rst
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/readme/CONTRIBUTORS.rst
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/tests/test_purchase_operating_unit.py
Labels: 13.0.project_mi_465

#134 [t118843] adding project_operating_unit module
  project_operating_unit/README.rst
  project_operating_unit/__init__.py
  project_operating_unit/__manifest__.py
  project_operating_unit/i18n/project_operating_unit.pot
  project_operating_unit/i18n/pt.po
  project_operating_unit/models/__init__.py
  project_operating_unit/models/project_project.py
  project_operating_unit/models/project_task.py
  project_operating_unit/readme/CONTRIBUTORS.rst
  project_operating_unit/readme/CREDITS.rst
  project_operating_unit/readme/DESCRIPTION.rst
  project_operating_unit/readme/USAGE.rst
  project_operating_unit/security/project_security.xml
  project_operating_unit/static/description/icon.png
  project_operating_unit/static/description/index.html
  project_operating_unit/tests/__init__.py
  project_operating_unit/tests/test_project_operating_unit.py
  project_operating_unit/views/project_project.xml
  project_operating_unit/views/project_task.xml
Labels: 13.0.project_pm_597

#137 Syncing from upstream OCA/operating-unit (13.0)
  hr_contract_operating_unit/README.rst
  hr_contract_operating_unit/__init__.py
  hr_contract_operating_unit/__manifest__.py
  hr_contract_operating_unit/i18n/hr_contract_operating_unit.pot
  hr_contract_operating_unit/i18n/pt.po
  hr_contract_operating_unit/models/__init__.py
  hr_contract_operating_unit/models/hr_contract.py
  hr_contract_operating_unit/readme/CONTRIBUTORS.rst
  hr_contract_operating_unit/readme/DESCRIPTION.rst
  hr_contract_operating_unit/readme/USAGE.rst
  hr_contract_operating_unit/security/hr_contract_security.xml
  hr_contract_operating_unit/static/description/icon.png
  hr_contract_operating_unit/static/description/index.html
  hr_contract_operating_unit/tests/__init__.py
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  hr_contract_operating_unit/views/hr_contract_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_contract_operating_unit/odoo/addons/hr_contract_operating_unit
  setup/hr_contract_operating_unit/setup.py
Labels: 13.0

#138 Syncing from upstream OCA/operating-unit (13.0)
  hr_contract_operating_unit/i18n/pt.po
  operating_unit/__manifest__.py
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/res_users.py
  operating_unit/security/operating_unit_security.xml
  operating_unit/tests/test_operating_unit.py
Labels: 13.0

#139 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/readme/CONFIGURE.rst
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/readme/DESCRIPTION.rst
  operating_unit/readme/ROADMAP.rst
  operating_unit/readme/USAGE.rst
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/operating_unit/odoo/addons/operating_unit
  setup/operating_unit/setup.py
Labels: 14.0

#141 Syncing from upstream OCA/operating-unit (12.0)
  product_operating_unit/__manifest__.py
  product_operating_unit/i18n/product_operating_unit.pot
  product_operating_unit/models/product_template.py
Labels: 12.0

#142 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  sales_team_operating_unit/README.rst
  sales_team_operating_unit/__init__.py
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/i18n/es_MX.po
  sales_team_operating_unit/i18n/sales_team_operating_unit.pot
  sales_team_operating_unit/models/__init__.py
  sales_team_operating_unit/models/crm_team.py
  sales_team_operating_unit/readme/CONTRIBUTORS.rst
  sales_team_operating_unit/readme/DESCRIPTION.rst
  sales_team_operating_unit/readme/USAGE.rst
  sales_team_operating_unit/security/crm_security.xml
  sales_team_operating_unit/static/description/icon.png
  sales_team_operating_unit/static/description/index.html
  sales_team_operating_unit/tests/__init__.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  sales_team_operating_unit/views/crm_team_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sales_team_operating_unit/odoo/addons/sales_team_operating_unit
  setup/sales_team_operating_unit/setup.py
Labels: 14.0

#144 [t113973] Preparing our 12.0.project_MI_465 for our Docker.
  .braintec/deploy.yaml
Labels: 12.0.project_mi_465

#145 [t113793] Preparing operating-unit for brain-tec's Docker.
  .braintec/deploy.yaml
  ext/.gitignore
Labels: 13.0.project_mi_465

#146 [t113973] Preparing operating-unit to brain-tec's Docker.
  .braintec/deploy.yaml
  ext/.gitignore
Labels: 12.0.project_mi_465

#147 Syncing from upstream OCA/operating-unit (13.0)
  .pre-commit-config.yaml
Labels: 13.0

#148 [t113973] Removing unneeded ext subfolder as the BT CLI was bugfixed …
  ext/.gitignore
Labels: 12.0.project_mi_465
