Repository brain-tec/operating-unit, pull requests merged in 2020-01, with the labels that each got.

#55 Syncing from upstream OCA/operating-unit (12.0)
  fieldservice_operating_unit/README.rst
  fieldservice_operating_unit/__init__.py
  fieldservice_operating_unit/__manifest__.py
  fieldservice_operating_unit/i18n/fieldservice_operating_unit.pot
  fieldservice_operating_unit/models/__init__.py
  fieldservice_operating_unit/models/fsm_order.py
  fieldservice_operating_unit/readme/CONTRIBUTORS.rst
  fieldservice_operating_unit/readme/CREDITS.rst
  fieldservice_operating_unit/readme/DESCRIPTION.rst
  fieldservice_operating_unit/readme/USAGE.rst
  fieldservice_operating_unit/security/fieldservice_security.xml
  fieldservice_operating_unit/static/description/icon.png
  fieldservice_operating_unit/static/description/index.html
  fieldservice_operating_unit/tests/__init__.py
  fieldservice_operating_unit/tests/test_fieldservice_operating_unit.py
  fieldservice_operating_unit/views/fsm_order.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/fieldservice_operating_unit/odoo/addons/fieldservice_operating_unit
  setup/fieldservice_operating_unit/setup.py
Labels: 12.0

#56 Syncing from upstream OCA/operating-unit (13.0)
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/readme/CONFIGURE.rst
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/readme/DESCRIPTION.rst
  operating_unit/readme/ROADMAP.rst
  operating_unit/readme/USAGE.rst
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/operating_unit/odoo/addons/operating_unit
  setup/operating_unit/setup.py
Labels: 13.0

#57 Syncing from upstream OCA/operating-unit (13.0)
  .isort.cfg
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/views/analytic_account_view.xml
  sales_team_operating_unit/README.rst
  sales_team_operating_unit/__init__.py
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/i18n/sales_team_operating_unit.pot
  sales_team_operating_unit/models/__init__.py
  sales_team_operating_unit/models/crm_team.py
  sales_team_operating_unit/readme/CONTRIBUTORS.rst
  sales_team_operating_unit/readme/DESCRIPTION.rst
  sales_team_operating_unit/readme/USAGE.rst
  sales_team_operating_unit/security/crm_security.xml
  sales_team_operating_unit/static/description/icon.png
  sales_team_operating_unit/static/description/index.html
  sales_team_operating_unit/tests/__init__.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  sales_team_operating_unit/views/crm_team_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/analytic_operating_unit/odoo/addons/analytic_operating_unit
  setup/analytic_operating_unit/setup.py
  setup/sales_team_operating_unit/odoo/addons/sales_team_operating_unit
  setup/sales_team_operating_unit/setup.py
Labels: 13.0

#59 Syncing from upstream OCA/operating-unit (12.0)
  agreement_operating_unit/README.rst
  agreement_operating_unit/__init__.py
  agreement_operating_unit/__manifest__.py
  agreement_operating_unit/i18n/agreement_operating_unit.pot
  agreement_operating_unit/models/__init__.py
  agreement_operating_unit/models/agreement.py
  agreement_operating_unit/models/agreement_serviceprofile.py
  agreement_operating_unit/readme/CONTRIBUTORS.rst
  agreement_operating_unit/readme/CREDITS.rst
  agreement_operating_unit/readme/DESCRIPTION.rst
  agreement_operating_unit/readme/USAGE.rst
  agreement_operating_unit/security/aggreement_security.xml
  agreement_operating_unit/static/description/icon.png
  agreement_operating_unit/static/description/index.html
  agreement_operating_unit/tests/__init__.py
  agreement_operating_unit/tests/test_agreement_operating_unit.py
  agreement_operating_unit/views/agreement.xml
  agreement_operating_unit/views/agreement_serviceprofile.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/agreement_operating_unit/odoo/addons/agreement_operating_unit
  setup/agreement_operating_unit/setup.py
Labels: 12.0

#60 Syncing from upstream OCA/operating-unit (12.0)
  project_operating_unit/tests/test_project_operating_unit.py
  res_partner_operating_unit/README.rst
  res_partner_operating_unit/__init__.py
  res_partner_operating_unit/__manifest__.py
  res_partner_operating_unit/i18n/res_partner_operating_unit.pot
  res_partner_operating_unit/models/__init__.py
  res_partner_operating_unit/models/res_partner.py
  res_partner_operating_unit/models/res_users.py
  res_partner_operating_unit/readme/CONTRIBUTORS.rst
  res_partner_operating_unit/readme/CREDITS.rst
  res_partner_operating_unit/readme/DESCRIPTION.rst
  res_partner_operating_unit/readme/USAGE.rst
  res_partner_operating_unit/security/res_partner_security.xml
  res_partner_operating_unit/static/description/icon.png
  res_partner_operating_unit/static/description/index.html
  res_partner_operating_unit/tests/__init__.py
  res_partner_operating_unit/tests/test_res_partner_operating_unit.py
  res_partner_operating_unit/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/res_partner_operating_unit/odoo/addons/res_partner_operating_unit
  setup/res_partner_operating_unit/setup.py
Labels: 12.0

#61 Syncing from upstream OCA/operating-unit (12.0)
  account_operating_unit/__manifest__.py
  account_operating_unit/views/invoice_view.xml
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/i18n/purchase_operating_unit.pot
  purchase_operating_unit/models/purchase_order.py
  sale_stock_operating_unit/__manifest__.py
  sale_stock_operating_unit/i18n/sale_stock_operating_unit.pot
  sale_stock_operating_unit/models/sale_order.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_warehouse.py
Labels: 12.0

#63 Syncing from upstream OCA/operating-unit (12.0)
  stock_operating_unit/__manifest__.py
  stock_operating_unit/security/stock_security.xml
Labels: 12.0

#64 [bt#9148] Made the tests to pass again.
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  crm_operating_unit/tests/test_crm_operating_unit.py
  fieldservice_operating_unit/tests/test_fieldservice_operating_unit.py
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  hr_expense_operating_unit/tests/test_hr_expense_operating_unit.py
  hr_payroll_account_operating_unit/tests/test_payroll_account_operating_unit.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  oca_dependencies.txt
  operating_unit/tests/OperatingUnitsTransactionCase.py
  operating_unit/tests/test_operating_unit.py
  partner_operating_unit/tests/test_res_partner_category_operating_unit.py
  partner_operating_unit/tests/test_res_partner_operating_unit.py
  product_operating_unit/tests/test_product_operating_unit.py
  project_operating_unit/tests/test_project_operating_unit.py
  purchase_operating_unit/tests/test_po_security.py
  purchase_operating_unit/tests/test_purchase_operating_unit.py
  purchase_request_operating_unit/tests/test_purchase_request_operating_unit.py
  purchase_request_operating_unit/tests/test_purchase_request_to_rfq_operating_unit.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_stock_operating_unit/models/sale_order.py
  sale_stock_operating_unit/tests/test_sale_stock_operating_unit.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  stock_account_operating_unit/model/stock_move.py
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
Labels: 12.0.project_mi_465

#69 [13.0][MIG] mrp_operating_unit
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/readme/CONTRIBUTORS.rst
  mrp_operating_unit/readme/DESCRIPTION.rst
  mrp_operating_unit/readme/USAGE.rst
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
Labels: 13.0.project_sv_559_temp

#70 [13.0][MIG] account_operating_unit
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/models/__init__.py
  account_operating_unit/models/account_journal.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_payment.py
  account_operating_unit/models/res_company.py
  account_operating_unit/readme/CONFIGURE.rst
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/readme/DESCRIPTION.rst
  account_operating_unit/readme/ROADMAP.rst
  account_operating_unit/readme/USAGE.rst
  account_operating_unit/report/__init__.py
  account_operating_unit/report/account_invoice_report.py
  account_operating_unit/security/account_security.xml
  account_operating_unit/static/description/icon.png
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/__init__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/views/account_invoice_report_view.xml
  account_operating_unit/views/account_journal_view.xml
  account_operating_unit/views/account_move_view.xml
  account_operating_unit/views/account_payment_view.xml
  account_operating_unit/views/company_view.xml
Labels: 13.0.project_sv_559_temp
