Repository brain-tec/operating-unit, pull requests merged in 2020-03, with the labels that each got.

#84 Syncing from upstream OCA/operating-unit (12.0)
  account_operating_unit/i18n/pt.po
  agreement_operating_unit/i18n/pt.po
  analytic_operating_unit/i18n/pt.po
  crm_operating_unit/i18n/pt.po
  fieldservice_operating_unit/i18n/pt.po
  hr_contract_operating_unit/i18n/pt.po
  hr_expense_operating_unit/i18n/pt.po
  hr_payroll_account_operating_unit/i18n/pt.po
  mrp_operating_unit/i18n/pt.po
  operating_unit/i18n/pt.po
  project_operating_unit/i18n/pt.po
  purchase_operating_unit/i18n/pt.po
  purchase_request_operating_unit/i18n/pt.po
  report_qweb_operating_unit/i18n/pt.po
  res_partner_operating_unit/i18n/pt.po
  sale_operating_unit/i18n/pt.po
  sale_stock_operating_unit/i18n/pt.po
  sales_team_operating_unit/i18n/pt.po
  stock_account_operating_unit/i18n/pt.po
  stock_operating_unit/i18n/pt.po
Labels: 12.0

#85 Syncing from upstream OCA/operating-unit (13.0)
  .editorconfig
  .eslintrc
  .eslintrc.yml
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .travis.yml
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/views/analytic_account_view.xml
  crm_operating_unit/security/crm_security.xml
  crm_operating_unit/views/crm_lead_view.xml
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/security/operating_unit_security.xml
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
  report_qweb_operating_unit/views/report_qweb_operating_unit.xml
  sales_team_operating_unit/security/crm_security.xml
  sales_team_operating_unit/views/crm_team_view.xml
Labels: 13.0

#86 Syncing from upstream OCA/operating-unit (12.0)
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/i18n/pt.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/model/__init__.py
  stock_operating_unit/models/__init__.py
  stock_operating_unit/models/product_product.py
  stock_operating_unit/models/stock_location.py
  stock_operating_unit/models/stock_move.py
  stock_operating_unit/models/stock_picking.py
  stock_operating_unit/models/stock_rule.py
  stock_operating_unit/models/stock_warehouse.py
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/view/stock.xml
  stock_operating_unit/view/stock_picking.xml
Labels: 12.0

#88 Syncing from upstream OCA/operating-unit (12.0)
  project_operating_unit/__manifest__.py
  project_operating_unit/i18n/project_operating_unit.pot
  project_operating_unit/i18n/pt.po
  project_operating_unit/views/project_project.xml
  stock_operating_unit/__manifest__.py
  stock_operating_unit/i18n/pt.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/models/stock_picking.py
Labels: 12.0

#89 Syncing from upstream OCA/operating-unit (12.0)
  account_operating_unit/i18n/da.po
Labels: 12.0

#90 Syncing from upstream OCA/operating-unit (12.0)
  res_partner_operating_unit/__manifest__.py
  res_partner_operating_unit/models/res_partner.py
  res_partner_operating_unit/security/res_partner_security.xml
  res_partner_operating_unit/views/res_partner_view.xml
Labels: 12.0

#91 Updating 12.0.project_MI_465 from latest 12.0
  account_operating_unit/i18n/da.po
  project_operating_unit/__manifest__.py
  project_operating_unit/i18n/project_operating_unit.pot
  project_operating_unit/i18n/pt.po
  project_operating_unit/views/project_project.xml
  res_partner_operating_unit/__manifest__.py
  res_partner_operating_unit/models/res_partner.py
  res_partner_operating_unit/security/res_partner_security.xml
  res_partner_operating_unit/views/res_partner_view.xml
  stock_operating_unit/__manifest__.py
  stock_operating_unit/i18n/pt.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/models/stock_picking.py
Labels: 12.0.project_mi_465

#92 Syncing from upstream OCA/operating-unit (12.0)
  stock_operating_unit/__manifest__.py
  stock_operating_unit/security/stock_security.xml
Labels: 12.0

#93 Syncing from upstream OCA/operating-unit (12.0)
  operating_unit/i18n/da.po
Labels: 12.0

#94 Syncing from upstream OCA/operating-unit (12.0)
  stock_operating_unit/__manifest__.py
  stock_operating_unit/i18n/pt.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/models/stock_move.py
Labels: 12.0
