Repository brain-tec/operating-unit, pull requests merged in 2021-02, with the labels that each got.

#164 Syncing from upstream OCA/operating-unit (12.0)
  sale_stock_operating_unit/i18n/it.po
Labels: 12.0

#165 Updating from latest OCA 12.0
  sale_stock_operating_unit/i18n/it.po
Labels: 12.0.project_mi_465

#166 [bt#13407] FI: CHF Journal Ignored due to OU Issue
  account_operating_unit/models/account_move.py
Labels: 13.0.project_mi_465

#167 [bt#12546] Bugfixing assignment of operating unit for pickings coming…
  sale_stock_operating_unit/models/stock_move.py
Labels: 13.0.project_mi_465, enhancement

#168 Syncing from upstream OCA/operating-unit (12.0)
  stock_operating_unit/i18n/it.po
Labels: 12.0

#169 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/models/__init__.py
  account_operating_unit/models/account_journal.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_payment.py
  account_operating_unit/models/res_company.py
  account_operating_unit/readme/CONFIGURE.rst
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/readme/DESCRIPTION.rst
  account_operating_unit/readme/ROADMAP.rst
  account_operating_unit/readme/USAGE.rst
  account_operating_unit/report/__init__.py
  account_operating_unit/report/account_invoice_report.py
  account_operating_unit/security/account_security.xml
  account_operating_unit/static/description/icon.png
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/__init__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/views/account_invoice_report_view.xml
  account_operating_unit/views/account_journal_view.xml
  account_operating_unit/views/account_move_view.xml
  account_operating_unit/views/account_payment_view.xml
  account_operating_unit/views/company_view.xml
  account_operating_unit/wizards/__init__.py
  account_operating_unit/wizards/account_payment_register.py
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/i18n/es_MX.po
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/readme/CONTRIBUTORS.rst
  analytic_operating_unit/readme/DESCRIPTION.rst
  analytic_operating_unit/readme/USAGE.rst
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/static/description/index.html
  analytic_operating_unit/views/analytic_account_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_operating_unit/odoo/addons/account_operating_unit
  setup/account_operating_unit/setup.py
  setup/analytic_operating_unit/odoo/addons/analytic_operating_unit
  setup/analytic_operating_unit/setup.py
Labels: 14.0
