Repository brain-tec/operating-unit, pull requests merged in 2021-12, with the labels that each got.

#260 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  mis_builder_budget_operating_unit/README.rst
  mis_builder_budget_operating_unit/__init__.py
  mis_builder_budget_operating_unit/__manifest__.py
  mis_builder_budget_operating_unit/i18n/mis_builder_budget_operating_unit.pot
  mis_builder_budget_operating_unit/models/__init__.py
  mis_builder_budget_operating_unit/models/mis_budget_item.py
  mis_builder_budget_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_budget_operating_unit/readme/DESCRIPTION.rst
  mis_builder_budget_operating_unit/readme/USAGE.rst
  mis_builder_budget_operating_unit/static/description/icon.png
  mis_builder_budget_operating_unit/static/description/index.html
  mis_builder_budget_operating_unit/views/mis_builder_budget.xml
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/i18n/da.po
  mis_builder_operating_unit/i18n/mis_builder_operating_unit.pot
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_operating_unit/readme/DESCRIPTION.rst
  mis_builder_operating_unit/readme/USAGE.rst
  mis_builder_operating_unit/security/mis_builder_security.xml
  mis_builder_operating_unit/static/description/icon.png
  mis_builder_operating_unit/static/description/index.html
  mis_builder_operating_unit/view/mis_builder.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mis_builder_budget_operating_unit/odoo/addons/mis_builder_budget_operating_unit
  setup/mis_builder_budget_operating_unit/setup.py
  setup/mis_builder_operating_unit/odoo/addons/mis_builder_operating_unit
  setup/mis_builder_operating_unit/setup.py
Labels: 14.0

#261 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/readme/CONFIGURE.rst
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/readme/DESCRIPTION.rst
  operating_unit/readme/ROADMAP.rst
  operating_unit/readme/USAGE.rst
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/operating_unit/odoo/addons/operating_unit
  setup/operating_unit/setup.py
Labels: 15.0

#262 [t121075] Fixes _onchange_operating_unit_id by adding limit=1 to search call
  mrp_operating_unit/models/mrp.py
Labels: 13.0.project_mi_465.test

#263 Syncing from upstream OCA/operating-unit (14.0)
  analytic_operating_unit/i18n/it.po
Labels: 14.0

#264 Syncing from upstream OCA/operating-unit (12.0)
  purchase_request_operating_unit/__manifest__.py
  purchase_request_operating_unit/i18n/pt.po
  purchase_request_operating_unit/i18n/purchase_request_operating_unit.pot
  purchase_request_operating_unit/wizard/purchase_request_line_make_purchase_order.py
Labels: 12.0

#265 Syncing from upstream OCA/operating-unit (13.0)
  operating_unit/__manifest__.py
  operating_unit/demo/operating_unit_demo.xml
Labels: 13.0

#266 Syncing from upstream OCA/operating-unit (12.0-ocabot-merge-pr-307-by-dreispt-bump-nobump)
  mail_template_operating_unit/i18n/mail_template_operating_unit.pot
Labels: 12.0-ocabot-merge-pr-307-by-dreispt-bump-nobump

#259 [t121075] Fixes _onchange_operating_unit_id by adding limit=1 to search call.
  mrp_operating_unit/models/mrp.py
Labels: 13.0.project_mi_465

#270 Fixed precommit hook error
  mrp_operating_unit/models/mrp.py
  sale_stock_operating_unit/__manifest__.py
  sale_stock_operating_unit/models/sale_order.py
Labels: 13.0.project_mi_465

#269 Merging 13.0 into 13.0.project_MI_465
  operating_unit/__manifest__.py
  operating_unit/demo/operating_unit_demo.xml
Labels: 13.0.project_mi_465

#272 Syncing from upstream OCA/operating-unit (12.0)
  mail_template_operating_unit/README.rst
  mail_template_operating_unit/__init__.py
  mail_template_operating_unit/__manifest__.py
  mail_template_operating_unit/i18n/mail_template_operating_unit.pot
  mail_template_operating_unit/models/__init__.py
  mail_template_operating_unit/models/mail.py
  mail_template_operating_unit/readme/CONTRIBUTORS.rst
  mail_template_operating_unit/readme/DESCRIPTION.rst
  mail_template_operating_unit/readme/USAGE.rst
  mail_template_operating_unit/security/mail_security.xml
  mail_template_operating_unit/static/description/icon.png
  mail_template_operating_unit/static/description/index.html
  mail_template_operating_unit/views/mail_template_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mail_template_operating_unit/odoo/addons/mail_template_operating_unit
  setup/mail_template_operating_unit/setup.py
Labels: 12.0

#271 Merging 13.0.project_mi_465 into 13.0.project_mi_465.test
  mrp_operating_unit/models/mrp.py
  operating_unit/__manifest__.py
  operating_unit/demo/operating_unit_demo.xml
  sale_stock_operating_unit/__manifest__.py
  sale_stock_operating_unit/models/sale_order.py
Labels: 13.0.project_mi_465.test

#273 Syncing from upstream OCA/operating-unit (14.0)
  mis_builder_operating_unit/i18n/it.po
Labels: 14.0

#274 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/i18n/es_MX.po
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/readme/CONTRIBUTORS.rst
  analytic_operating_unit/readme/DESCRIPTION.rst
  analytic_operating_unit/readme/USAGE.rst
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/static/description/index.html
  analytic_operating_unit/views/analytic_account_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/analytic_operating_unit/odoo/addons/analytic_operating_unit
  setup/analytic_operating_unit/setup.py
Labels: 15.0

#276 Syncing from upstream OCA/operating-unit (12.0)
  mis_builder_operating_unit/i18n/it.po
Labels: 12.0

#277 Syncing from upstream OCA/operating-unit (14.0)
  mis_builder_operating_unit/i18n/it.po
Labels: 14.0

#278 Syncing from upstream OCA/operating-unit (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_account_operating_unit/odoo/addons/stock_account_operating_unit
  setup/stock_account_operating_unit/setup.py
  stock_account_operating_unit/README.rst
  stock_account_operating_unit/__init__.py
  stock_account_operating_unit/__manifest__.py
  stock_account_operating_unit/i18n/stock_account_operating_unit.pot
  stock_account_operating_unit/model/__init__.py
  stock_account_operating_unit/model/stock_move.py
  stock_account_operating_unit/readme/CONFIGURATION.rst
  stock_account_operating_unit/readme/CONTRIBUTORS.rst
  stock_account_operating_unit/readme/DESCRIPTION.rst
  stock_account_operating_unit/readme/USAGE.rst
  stock_account_operating_unit/static/description/icon.png
  stock_account_operating_unit/static/description/index.html
  stock_account_operating_unit/tests/__init__.py
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
Labels: 13.0
