Repository brain-tec/operating-unit, pull requests merged in 2021-11, with the labels that each got.

#221 [t124337] Fixing onchanges in SO
  sale_stock_operating_unit/__manifest__.py
  sale_stock_operating_unit/models/sale_order.py
Labels: 13.0.project_mi_465

#251 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  hr_expense_operating_unit_access_all/README.rst
  hr_expense_operating_unit_access_all/__init__.py
  hr_expense_operating_unit_access_all/__manifest__.py
  hr_expense_operating_unit_access_all/i18n/hr_expense_operating_unit_access_all.pot
  hr_expense_operating_unit_access_all/readme/CONFIGURE.rst
  hr_expense_operating_unit_access_all/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit_access_all/readme/DESCRIPTION.rst
  hr_expense_operating_unit_access_all/security/hr_expense_security.xml
  hr_expense_operating_unit_access_all/static/description/icon.png
  hr_expense_operating_unit_access_all/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_expense_operating_unit_access_all/odoo/addons/hr_expense_operating_unit_access_all
  setup/hr_expense_operating_unit_access_all/setup.py
Labels: 14.0

#252 Syncing from upstream OCA/operating-unit (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
Labels: 14.0

#253 Syncing from upstream OCA/operating-unit (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
Labels: 15.0

#255 [t126094][MIG] operating_unit: Migration to 15.0
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/readme/CONFIGURE.rst
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/readme/DESCRIPTION.rst
  operating_unit/readme/ROADMAP.rst
  operating_unit/readme/USAGE.rst
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
  setup/operating_unit/odoo/addons/operating_unit
  setup/operating_unit/setup.py
Labels: 15.0.project_mi_465

#256 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  crm_operating_unit/README.rst
  crm_operating_unit/__init__.py
  crm_operating_unit/__manifest__.py
  crm_operating_unit/i18n/crm_operating_unit.pot
  crm_operating_unit/i18n/es.po
  crm_operating_unit/i18n/es_MX.po
  crm_operating_unit/models/__init__.py
  crm_operating_unit/models/crm_lead.py
  crm_operating_unit/readme/CONTRIBUTORS.rst
  crm_operating_unit/readme/DESCRIPTION.rst
  crm_operating_unit/readme/USAGE.rst
  crm_operating_unit/security/crm_security.xml
  crm_operating_unit/static/description/icon.png
  crm_operating_unit/static/description/index.html
  crm_operating_unit/tests/__init__.py
  crm_operating_unit/tests/test_crm_operating_unit.py
  crm_operating_unit/views/crm_lead_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/crm_operating_unit/odoo/addons/crm_operating_unit
  setup/crm_operating_unit/setup.py
Labels: 14.0

#258 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  purchase_operating_unit_access_all/README.rst
  purchase_operating_unit_access_all/__init__.py
  purchase_operating_unit_access_all/__manifest__.py
  purchase_operating_unit_access_all/i18n/purchase_operating_unit_access_all.pot
  purchase_operating_unit_access_all/readme/CONFIGURE.rst
  purchase_operating_unit_access_all/readme/CONTRIBUTORS.rst
  purchase_operating_unit_access_all/readme/DESCRIPTION.rst
  purchase_operating_unit_access_all/security/purchase_security.xml
  purchase_operating_unit_access_all/static/description/icon.png
  purchase_operating_unit_access_all/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_operating_unit_access_all/odoo/addons/purchase_operating_unit_access_all
  setup/purchase_operating_unit_access_all/setup.py
Labels: 14.0
