Repository brain-tec/operating-unit, pull requests merged in 2021-05, with the labels that each got.

#177 Syncing from upstream OCA/operating-unit (12.0)
  hr_payroll_account_operating_unit/models/account_move.py
  mis_builder_budget_operating_unit/README.rst
  mis_builder_budget_operating_unit/__init__.py
  mis_builder_budget_operating_unit/__manifest__.py
  mis_builder_budget_operating_unit/i18n/mis_builder_budget_operating_unit.pot
  mis_builder_budget_operating_unit/models/__init__.py
  mis_builder_budget_operating_unit/models/mis_budget_item.py
  mis_builder_budget_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_budget_operating_unit/readme/DESCRIPTION.rst
  mis_builder_budget_operating_unit/readme/USAGE.rst
  mis_builder_budget_operating_unit/static/description/icon.png
  mis_builder_budget_operating_unit/static/description/index.html
  mis_builder_budget_operating_unit/views/mis_builder_budget.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mis_builder_budget_operating_unit/odoo/addons/mis_builder_budget_operating_unit
  setup/mis_builder_budget_operating_unit/setup.py
Labels: 12.0

#179 Syncing from upstream OCA/operating-unit (14.0)
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_payment_operating_unit.py
Labels: 14.0

#180 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  operating_unit/__manifest__.py
  operating_unit/models/operating_unit.py
Labels: 14.0

#181 Syncing from upstream OCA/operating-unit (12.0)
  purchase_operating_unit/README.rst
  purchase_operating_unit/__init__.py
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/i18n/pt.po
  purchase_operating_unit/i18n/purchase_operating_unit.pot
  purchase_operating_unit/readme/CONTRIBUTORS.rst
  purchase_operating_unit/report/__init__.py
  purchase_operating_unit/report/purchase_report.py
  purchase_operating_unit/static/description/index.html
Labels: 12.0

#182 Syncing from upstream OCA/operating-unit (13.0)
  sale_operating_unit_sequence/README.rst
  sale_operating_unit_sequence/__init__.py
  sale_operating_unit_sequence/__manifest__.py
  sale_operating_unit_sequence/hooks.py
  sale_operating_unit_sequence/i18n/sale_operating_unit_sequence.pot
  sale_operating_unit_sequence/models/__init__.py
  sale_operating_unit_sequence/models/operating_unit.py
  sale_operating_unit_sequence/models/sale_order.py
  sale_operating_unit_sequence/readme/CONFIGURE.rst
  sale_operating_unit_sequence/readme/CONTRIBUTORS.rst
  sale_operating_unit_sequence/readme/DESCRIPTION.rst
  sale_operating_unit_sequence/static/description/icon.png
  sale_operating_unit_sequence/static/description/index.html
  sale_operating_unit_sequence/tests/__init__.py
  sale_operating_unit_sequence/tests/test_sale_operating_unit_sequence.py
  sale_operating_unit_sequence/views/operating_unit_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_operating_unit_sequence/odoo/addons/sale_operating_unit_sequence
  setup/sale_operating_unit_sequence/setup.py
Labels: 13.0

#183 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_operating_unit/odoo/addons/stock_operating_unit
  setup/stock_operating_unit/setup.py
  stock_operating_unit/README.rst
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/data/stock_data.xml
  stock_operating_unit/demo/stock_demo.xml
  stock_operating_unit/hooks.py
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/model/__init__.py
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_move.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/readme/CONFIGURE.rst
  stock_operating_unit/readme/CONTRIBUTORS.rst
  stock_operating_unit/readme/DESCRIPTION.rst
  stock_operating_unit/readme/ROADMAP.rst
  stock_operating_unit/readme/USAGE.rst
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/index.html
  stock_operating_unit/tests/__init__.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
  stock_operating_unit/view/stock.xml
Labels: 14.0

#187 Syncing from upstream OCA/operating-unit (14.0)
  .copier-answers.yml
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
Labels: 14.0

#188 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  account_financial_report_operating_unit/README.rst
  account_financial_report_operating_unit/__init__.py
  account_financial_report_operating_unit/__manifest__.py
  account_financial_report_operating_unit/i18n/account_financial_report_operating_unit.pot
  account_financial_report_operating_unit/readme/CONTRIBUTORS.rst
  account_financial_report_operating_unit/readme/DESCRIPTION.rst
  account_financial_report_operating_unit/report/__init__.py
  account_financial_report_operating_unit/report/aged_partner_balance.py
  account_financial_report_operating_unit/report/general_ledger.py
  account_financial_report_operating_unit/report/journal_ledger.py
  account_financial_report_operating_unit/report/open_items.py
  account_financial_report_operating_unit/report/trial_balance.py
  account_financial_report_operating_unit/report/vat_report.py
  account_financial_report_operating_unit/static/description/icon.png
  account_financial_report_operating_unit/static/description/index.html
  account_financial_report_operating_unit/wizards/__init__.py
  account_financial_report_operating_unit/wizards/aged_partner_balance_wizard.py
  account_financial_report_operating_unit/wizards/aged_partner_balance_wizard_view.xml
  account_financial_report_operating_unit/wizards/general_ledger_wizard.py
  account_financial_report_operating_unit/wizards/general_ledger_wizard_view.xml
  account_financial_report_operating_unit/wizards/journal_ledger_wizard.py
  account_financial_report_operating_unit/wizards/journal_ledger_wizard_view.xml
  account_financial_report_operating_unit/wizards/open_items_wizard.py
  account_financial_report_operating_unit/wizards/open_items_wizard_view.xml
  account_financial_report_operating_unit/wizards/trial_balance_wizard.py
  account_financial_report_operating_unit/wizards/trial_balance_wizard_view.xml
  account_financial_report_operating_unit/wizards/vat_report_wizard.py
  account_financial_report_operating_unit/wizards/vat_report_wizard_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_financial_report_operating_unit/odoo/addons/account_financial_report_operating_unit
  setup/account_financial_report_operating_unit/setup.py
Labels: 14.0

#189 Update 20210524 - operating-unit - OCA 13.0
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/i18n/da.po
  mis_builder_operating_unit/i18n/mis_builder_operating_unit.pot
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_operating_unit/readme/DESCRIPTION.rst
  mis_builder_operating_unit/readme/USAGE.rst
  mis_builder_operating_unit/security/mis_builder_security.xml
  mis_builder_operating_unit/static/description/icon.png
  mis_builder_operating_unit/static/description/index.html
  mis_builder_operating_unit/tests/__init__.py
  mis_builder_operating_unit/tests/test_mis_builder_operating_unit.py
  mis_builder_operating_unit/view/mis_builder.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mis_builder_operating_unit/odoo/addons/mis_builder_operating_unit
  setup/mis_builder_operating_unit/setup.py
Labels: 13.0.project_mi_465

#190 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  purchase_operating_unit/README.rst
  purchase_operating_unit/__init__.py
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/demo/purchase_order_demo.xml
  purchase_operating_unit/i18n/purchase_operating_unit.pot
  purchase_operating_unit/models/__init__.py
  purchase_operating_unit/models/account_invoice.py
  purchase_operating_unit/models/purchase_order.py
  purchase_operating_unit/readme/CONTRIBUTORS.rst
  purchase_operating_unit/readme/DESCRIPTION.rst
  purchase_operating_unit/readme/ROADMAP.rst
  purchase_operating_unit/readme/USAGE.rst
  purchase_operating_unit/security/purchase_security.xml
  purchase_operating_unit/static/description/icon.png
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/tests/__init__.py
  purchase_operating_unit/tests/test_po_security.py
  purchase_operating_unit/tests/test_purchase_operating_unit.py
  purchase_operating_unit/views/purchase_order_line_view.xml
  purchase_operating_unit/views/purchase_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_operating_unit/odoo/addons/purchase_operating_unit
  setup/purchase_operating_unit/setup.py
Labels: 14.0
