Repository brain-tec/operating-unit, pull requests merged in 2021-06, with the labels that each got.

#191 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  hr_expense_operating_unit/README.rst
  hr_expense_operating_unit/__init__.py
  hr_expense_operating_unit/__manifest__.py
  hr_expense_operating_unit/i18n/hr_expense_operating_unit.pot
  hr_expense_operating_unit/models/__init__.py
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit/readme/DESCRIPTION.rst
  hr_expense_operating_unit/readme/USAGE.rst
  hr_expense_operating_unit/security/hr_expense_security.xml
  hr_expense_operating_unit/static/description/icon.png
  hr_expense_operating_unit/static/description/index.html
  hr_expense_operating_unit/tests/__init__.py
  hr_expense_operating_unit/tests/test_hr_expense_operating_unit.py
  hr_expense_operating_unit/views/hr_expense_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_expense_operating_unit/odoo/addons/hr_expense_operating_unit
  setup/hr_expense_operating_unit/setup.py
Labels: 14.0

#192 Syncing from upstream OCA/operating-unit (12.0)
  mis_builder_budget_operating_unit/i18n/da.po
Labels: 12.0

#193 Syncing from upstream OCA/operating-unit (12.0)
  account_operating_unit/i18n/it.po
  sale_stock_operating_unit/i18n/it.po
Labels: 12.0

#194 Syncing from upstream OCA/operating-unit (13.0)
  mis_builder_budget_operating_unit/README.rst
  mis_builder_budget_operating_unit/__init__.py
  mis_builder_budget_operating_unit/__manifest__.py
  mis_builder_budget_operating_unit/i18n/mis_builder_budget_operating_unit.pot
  mis_builder_budget_operating_unit/models/__init__.py
  mis_builder_budget_operating_unit/models/mis_budget_item.py
  mis_builder_budget_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_budget_operating_unit/readme/DESCRIPTION.rst
  mis_builder_budget_operating_unit/readme/USAGE.rst
  mis_builder_budget_operating_unit/static/description/icon.png
  mis_builder_budget_operating_unit/static/description/index.html
  mis_builder_budget_operating_unit/views/mis_builder_budget.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mis_builder_budget_operating_unit/odoo/addons/mis_builder_budget_operating_unit
  setup/mis_builder_budget_operating_unit/setup.py
Labels: 13.0

#195 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  operating_unit_access_all/README.rst
  operating_unit_access_all/__init__.py
  operating_unit_access_all/__manifest__.py
  operating_unit_access_all/i18n/operating_unit_access_all.pot
  operating_unit_access_all/readme/CONFIGURE.rst
  operating_unit_access_all/readme/CONTRIBUTORS.rst
  operating_unit_access_all/readme/DESCRIPTION.rst
  operating_unit_access_all/security/operating_unit_security.xml
  operating_unit_access_all/static/description/icon.png
  operating_unit_access_all/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/operating_unit_access_all/odoo/addons/operating_unit_access_all
  setup/operating_unit_access_all/setup.py
Labels: 14.0

#196 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  contract_operating_unit/README.rst
  contract_operating_unit/__init__.py
  contract_operating_unit/__manifest__.py
  contract_operating_unit/i18n/contract_operating_unit.pot
  contract_operating_unit/models/__init__.py
  contract_operating_unit/models/contract.py
  contract_operating_unit/readme/CONTRIBUTORS.rst
  contract_operating_unit/readme/DESCRIPTION.rst
  contract_operating_unit/readme/USAGE.rst
  contract_operating_unit/security/contract_security.xml
  contract_operating_unit/static/description/icon.png
  contract_operating_unit/static/description/index.html
  contract_operating_unit/tests/__init__.py
  contract_operating_unit/tests/test_contract_operating_unit.py
  contract_operating_unit/views/contract_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/contract_operating_unit/odoo/addons/contract_operating_unit
  setup/contract_operating_unit/setup.py
Labels: 14.0

#198 Backmerge from 12.0 into 12.0.project_MI_465
  account_operating_unit/i18n/it.po
  mis_builder_budget_operating_unit/i18n/da.po
  sale_stock_operating_unit/i18n/it.po
Labels: 12.0.project_mi_465

#197 Backmerge from 13.0 into 13.0.project_MI_465
  mis_builder_budget_operating_unit/README.rst
  mis_builder_budget_operating_unit/__init__.py
  mis_builder_budget_operating_unit/__manifest__.py
  mis_builder_budget_operating_unit/i18n/mis_builder_budget_operating_unit.pot
  mis_builder_budget_operating_unit/models/__init__.py
  mis_builder_budget_operating_unit/models/mis_budget_item.py
  mis_builder_budget_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_budget_operating_unit/readme/DESCRIPTION.rst
  mis_builder_budget_operating_unit/readme/USAGE.rst
  mis_builder_budget_operating_unit/static/description/icon.png
  mis_builder_budget_operating_unit/static/description/index.html
  mis_builder_budget_operating_unit/views/mis_builder_budget.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mis_builder_budget_operating_unit/odoo/addons/mis_builder_budget_operating_unit
  setup/mis_builder_budget_operating_unit/setup.py
Labels: 13.0.project_mi_465

#201 [t119812][mt10054][mt10451] migration of 'mail_operating_unit' to v13.0
  mail_operating_unit/LICENSE
  mail_operating_unit/README.rst
  mail_operating_unit/__init__.py
  mail_operating_unit/__manifest__.py
  mail_operating_unit/data/mail_data.xml
  mail_operating_unit/models/__init__.py
  mail_operating_unit/models/mail_alias_ext.py
  mail_operating_unit/models/mail_mail_ext.py
  mail_operating_unit/models/mail_template_ext.py
  mail_operating_unit/models/operating_unit.py
  mail_operating_unit/models/res_users.py
  mail_operating_unit/readme/CONTRIBUTORS.rst
  mail_operating_unit/readme/DESCRIPTION.rst
  mail_operating_unit/readme/ROADMAP.rst
  mail_operating_unit/readme/USAGE.rst
  mail_operating_unit/security/mail_alias_security.xml
  mail_operating_unit/security/mail_template_security.xml
  mail_operating_unit/static/description/icon.png
  mail_operating_unit/static/description/index.html
  mail_operating_unit/views/mail_alias_views_ext.xml
  mail_operating_unit/views/mail_template_views_ext.xml
  mail_operating_unit/views/operating_unit_views_ext.xml
  mail_operating_unit/views/res_users_view.xml
  mail_operating_unit/wizard/__init__.py
  mail_operating_unit/wizard/mail_compose_message_ext.py
  mail_operating_unit/wizard/mail_compose_message_view_ext.xml
Labels: 13.0.project_mi_465.test

#202 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  oca_dependencies.txt
  purchase_request_operating_unit/README.rst
  purchase_request_operating_unit/__init__.py
  purchase_request_operating_unit/__manifest__.py
  purchase_request_operating_unit/i18n/pt.po
  purchase_request_operating_unit/i18n/purchase_request_operating_unit.pot
  purchase_request_operating_unit/model/__init__.py
  purchase_request_operating_unit/model/purchase_request.py
  purchase_request_operating_unit/readme/CONTRIBUTORS.rst
  purchase_request_operating_unit/readme/DESCRIPTION.rst
  purchase_request_operating_unit/readme/USAGE.rst
  purchase_request_operating_unit/security/purchase_security.xml
  purchase_request_operating_unit/static/description/icon.png
  purchase_request_operating_unit/static/description/index.html
  purchase_request_operating_unit/tests/__init__.py
  purchase_request_operating_unit/tests/test_purchase_request_operating_unit.py
  purchase_request_operating_unit/tests/test_purchase_request_to_rfq_operating_unit.py
  purchase_request_operating_unit/view/purchase_request_view.xml
  purchase_request_operating_unit/wizard/__init__.py
  purchase_request_operating_unit/wizard/purchase_request_line_make_purchase_order.py
  purchase_request_operating_unit/wizard/purchase_request_line_make_purchase_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_request_operating_unit/odoo/addons/purchase_request_operating_unit
  setup/purchase_request_operating_unit/setup.py
Labels: 14.0

#203 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  analytic_operating_unit_access_all/README.rst
  analytic_operating_unit_access_all/__init__.py
  analytic_operating_unit_access_all/__manifest__.py
  analytic_operating_unit_access_all/i18n/analytic_operating_unit_access_all.pot
  analytic_operating_unit_access_all/readme/CONFIGURE.rst
  analytic_operating_unit_access_all/readme/CONTRIBUTORS.rst
  analytic_operating_unit_access_all/readme/DESCRIPTION.rst
  analytic_operating_unit_access_all/security/analytic_security.xml
  analytic_operating_unit_access_all/static/description/icon.png
  analytic_operating_unit_access_all/static/description/index.html
  operating_unit/i18n/es_AR.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/analytic_operating_unit_access_all/odoo/addons/analytic_operating_unit_access_all
  setup/analytic_operating_unit_access_all/setup.py
Labels: 14.0

#204 Syncing from upstream OCA/operating-unit (14.0)
  operating_unit/i18n/es_AR.po
Labels: 14.0
