Repository brain-tec/operating-unit, pull requests merged in 2021-08, with the labels that each got.

#209 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/models/purchase_order.py
Labels: 14.0

#210 Syncing from upstream OCA/operating-unit (12.0)
  res_partner_operating_unit/__manifest__.py
  res_partner_operating_unit/models/res_users.py
Labels: 12.0

#211 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  agreement_operating_unit/README.rst
  agreement_operating_unit/__init__.py
  agreement_operating_unit/__manifest__.py
  agreement_operating_unit/i18n/agreement_operating_unit.pot
  agreement_operating_unit/i18n/pt.po
  agreement_operating_unit/models/__init__.py
  agreement_operating_unit/models/agreement.py
  agreement_operating_unit/models/agreement_serviceprofile.py
  agreement_operating_unit/readme/CONTRIBUTORS.rst
  agreement_operating_unit/readme/CREDITS.rst
  agreement_operating_unit/readme/DESCRIPTION.rst
  agreement_operating_unit/readme/USAGE.rst
  agreement_operating_unit/security/aggreement_security.xml
  agreement_operating_unit/static/description/icon.png
  agreement_operating_unit/static/description/index.html
  agreement_operating_unit/tests/__init__.py
  agreement_operating_unit/tests/test_agreement_operating_unit.py
  agreement_operating_unit/views/agreement.xml
  agreement_operating_unit/views/agreement_serviceprofile.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/agreement_operating_unit/odoo/addons/agreement_operating_unit
  setup/agreement_operating_unit/setup.py
Labels: 14.0

#212 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  product_operating_unit/README.rst
  product_operating_unit/__init__.py
  product_operating_unit/__manifest__.py
  product_operating_unit/i18n/product_operating_unit.pot
  product_operating_unit/i18n/pt.po
  product_operating_unit/models/__init__.py
  product_operating_unit/models/product_category.py
  product_operating_unit/models/product_template.py
  product_operating_unit/readme/CONTRIBUTORS.rst
  product_operating_unit/readme/DESCRIPTION.rst
  product_operating_unit/readme/ROADMAP.rst
  product_operating_unit/readme/USAGE.rst
  product_operating_unit/security/product_template_security.xml
  product_operating_unit/static/description/icon.png
  product_operating_unit/static/description/index.html
  product_operating_unit/tests/__init__.py
  product_operating_unit/tests/test_product_operating_unit.py
  product_operating_unit/views/product_category_view.xml
  product_operating_unit/views/product_template_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_operating_unit/odoo/addons/product_operating_unit
  setup/product_operating_unit/setup.py
Labels: 14.0

#213 Syncing from upstream OCA/operating-unit (12.0)
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/views/analytic_account_view.xml
Labels: 12.0

#214 Syncing from upstream OCA/operating-unit (8.0)
  README.md
Labels: 8.0

#215 Syncing from upstream OCA/operating-unit (9.0)
  README.md
Labels: 9.0

#216 Syncing from upstream OCA/operating-unit (14.0)
  README.md
Labels: 14.0

#217 Syncing from upstream OCA/operating-unit (10.0)
  README.md
Labels: 10.0

#218 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  stock_operating_unit/__manifest__.py
  stock_operating_unit/model/stock_warehouse.py
Labels: 14.0

#219 Syncing from upstream OCA/operating-unit (12.0)
  product_operating_unit/i18n/it.po
  purchase_operating_unit/i18n/it.po
  report_qweb_operating_unit/i18n/it.po
  res_partner_operating_unit/i18n/it.po
  sale_multi_operating_unit/i18n/it.po
  sale_operating_unit/i18n/it.po
Labels: 12.0

#220 [t124337] Fixing onchanges in SO
  sale_stock_operating_unit/__manifest__.py
  sale_stock_operating_unit/models/sale_order.py
Labels: 13.0.project_mi_465.test

#224 Update from latest OCA 12.0
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/views/analytic_account_view.xml
  product_operating_unit/i18n/it.po
  purchase_operating_unit/i18n/it.po
  report_qweb_operating_unit/i18n/it.po
  res_partner_operating_unit/__manifest__.py
  res_partner_operating_unit/i18n/it.po
  res_partner_operating_unit/models/res_users.py
  sale_multi_operating_unit/i18n/it.po
  sale_operating_unit/i18n/it.po
Labels: 12.0.project_mi_465
