Repository brain-tec/operating-unit, pull requests merged in 2021-10, with the labels that each got.

#233 Syncing from upstream OCA/operating-unit (8.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 8.0

#234 Syncing from upstream OCA/operating-unit (9.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 9.0

#235 Syncing from upstream OCA/operating-unit (10.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 10.0

#236 Syncing from upstream OCA/operating-unit (11.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 11.0

#237 Syncing from upstream OCA/operating-unit (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 12.0

#238 Syncing from upstream OCA/operating-unit (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 13.0

#230 Updated deploy.yaml with repositories needed (OCA dependencies)
  .braintec/deploy.yaml
Labels: enhancement, 13.0.project_mi_465

#248 Syncing from upstream OCA/operating-unit (15.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 15.0

#249 Syncing from upstream OCA/operating-unit (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .pre-commit-config.yaml
  README.md
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/views/purchase_order_view.xml
Labels: 14.0

#250 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  product_operating_unit/__manifest__.py
  product_operating_unit/models/product_template.py
Labels: 14.0
