Repository brain-tec/operating-unit, pull requests merged in 2022-04, with the labels that each got.

#307 Syncing from upstream OCA/operating-unit (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  account_asset_operating_unit/tests/test_account_asset_operating_unit.py
  account_operating_unit/tests/test_payment_operating_unit.py
  agreement_operating_unit/tests/test_agreement_operating_unit.py
  crm_operating_unit/tests/test_crm_operating_unit.py
  fieldservice_operating_unit/tests/test_fieldservice_operating_unit.py
  operating_unit/tests/test_operating_unit.py
  product_operating_unit/tests/test_product_operating_unit.py
  purchase_operating_unit/tests/test_purchase_operating_unit.py
  purchase_request_operating_unit/tests/test_purchase_request_operating_unit.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  stock_operating_unit/tests/test_stock_operating_unit.py
Labels: 14.0

#308 Syncing from upstream OCA/operating-unit (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0

#309 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  stock_operating_unit_access_all/__manifest__.py
  stock_operating_unit_access_all/security/stock_security.xml
Labels: 14.0

#310 Updating from latest OCA 15.0
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0.project_mi_465

#311 Syncing from upstream OCA/operating-unit (14.0)
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  .test.yml
  README.md
  account_asset_operating_unit_access_all/README.rst
  account_asset_operating_unit_access_all/__manifest__.py
  account_asset_operating_unit_access_all/static/description/index.html
  account_operating_unit/__manifest__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  contract_operating_unit/README.rst
  contract_operating_unit/__init__.py
  contract_operating_unit/__manifest__.py
  contract_operating_unit/models/contract.py
  contract_operating_unit/static/description/index.html
  contract_operating_unit/tests/test_contract_operating_unit.py
  mis_builder_budget_operating_unit/README.rst
  mis_builder_budget_operating_unit/__manifest__.py
  mis_builder_budget_operating_unit/models/mis_budget_item.py
  mis_builder_budget_operating_unit/static/description/index.html
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/static/description/index.html
Labels: 14.0

#312 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  account_financial_report_operating_unit/__manifest__.py
  account_financial_report_operating_unit/report/aged_partner_balance.py
  account_financial_report_operating_unit/report/open_items.py
  purchase_requisition_operating_unit/__manifest__.py
  purchase_requisition_operating_unit/view/purchase_requisition.xml
Labels: 14.0
