Repository brain-tec/operating-unit, pull requests merged in 2022-05, with the labels that each got.

#313 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/readme/CONTRIBUTORS.rst
  mrp_operating_unit/readme/DESCRIPTION.rst
  mrp_operating_unit/readme/USAGE.rst
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mrp_operating_unit/odoo/addons/mrp_operating_unit
  setup/mrp_operating_unit/setup.py
Labels: 14.0

#314 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  mis_builder_operating_unit_access_all/README.rst
  mis_builder_operating_unit_access_all/__init__.py
  mis_builder_operating_unit_access_all/__manifest__.py
  mis_builder_operating_unit_access_all/readme/CONFIGURE.rst
  mis_builder_operating_unit_access_all/readme/CONTRIBUTORS.rst
  mis_builder_operating_unit_access_all/readme/DESCRIPTION.rst
  mis_builder_operating_unit_access_all/security/mis_builder_security.xml
  mis_builder_operating_unit_access_all/static/description/icon.png
  mis_builder_operating_unit_access_all/static/description/index.html
  report_qweb_operating_unit/README.rst
  report_qweb_operating_unit/__init__.py
  report_qweb_operating_unit/__manifest__.py
  report_qweb_operating_unit/i18n/es_MX.po
  report_qweb_operating_unit/i18n/report_qweb_operating_unit.pot
  report_qweb_operating_unit/readme/CONTRIBUTORS.rst
  report_qweb_operating_unit/readme/DESCRIPTION.rst
  report_qweb_operating_unit/static/description/icon.png
  report_qweb_operating_unit/static/description/index.html
  report_qweb_operating_unit/views/report_qweb_operating_unit.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mis_builder_operating_unit_access_all/odoo/addons/mis_builder_operating_unit_access_all
  setup/mis_builder_operating_unit_access_all/setup.py
  setup/report_qweb_operating_unit/odoo/addons/report_qweb_operating_unit
  setup/report_qweb_operating_unit/setup.py
Labels: 14.0

#317 Syncing from upstream OCA/operating-unit (12.0)
  hr_operating_unit/README.rst
  hr_operating_unit/__init__.py
  hr_operating_unit/__manifest__.py
  hr_operating_unit/i18n/es.po
  hr_operating_unit/i18n/hr_operating_unit.pot
  hr_operating_unit/models/__init__.py
  hr_operating_unit/models/hr_employee.py
  hr_operating_unit/models/hr_operating_unit.py
  hr_operating_unit/readme/CONTRIBUTORS.rst
  hr_operating_unit/readme/DESCRIPTION.rst
  hr_operating_unit/readme/USAGE.rst
  hr_operating_unit/security/security.xml
  hr_operating_unit/static/description/icon.png
  hr_operating_unit/static/description/index.html
  hr_operating_unit/views/hr_employee.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_operating_unit/odoo/addons/hr_operating_unit
  setup/hr_operating_unit/setup.py
Labels: 12.0

#318 14.0 mig sale operating unit
  sale_operating_unit/README.rst
  sale_operating_unit/__init__.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/i18n/sale_operating_unit.pot
  sale_operating_unit/models/__init__.py
  sale_operating_unit/models/crm_team.py
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/readme/CONTRIBUTORS.rst
  sale_operating_unit/readme/DESCRIPTION.rst
  sale_operating_unit/readme/USAGE.rst
  sale_operating_unit/report/__init__.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/security/sale_security.xml
  sale_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/index.html
  sale_operating_unit/tests/__init__.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_operating_unit/views/sale_report_view.xml
  sale_operating_unit/views/sale_view.xml
  sale_operating_unit/wizard/__init__.py
  sale_operating_unit/wizard/sale_make_invoice_advance.py
  setup/sale_operating_unit/odoo/addons/sale_operating_unit
  setup/sale_operating_unit/setup.py
Labels: 14.0.project-sale-operating-unit

#323 14.0 mig sale operating unit
  sale_operating_unit/README.rst
  sale_operating_unit/__init__.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/i18n/sale_operating_unit.pot
  sale_operating_unit/models/__init__.py
  sale_operating_unit/models/crm_team.py
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/readme/CONTRIBUTORS.rst
  sale_operating_unit/readme/DESCRIPTION.rst
  sale_operating_unit/readme/USAGE.rst
  sale_operating_unit/report/__init__.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/security/sale_security.xml
  sale_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/index.html
  sale_operating_unit/tests/__init__.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_operating_unit/views/sale_report_view.xml
  sale_operating_unit/views/sale_view.xml
  sale_operating_unit/wizard/__init__.py
  sale_operating_unit/wizard/sale_make_invoice_advance.py
  setup/sale_operating_unit/odoo/addons/sale_operating_unit
  setup/sale_operating_unit/setup.py
Labels: 14.0-oca-sale-operating-unit
