Repository brain-tec/operating-unit, pull requests merged in 2022-01, with the labels that each got.

#283 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  stock_operating_unit/__manifest__.py
  stock_operating_unit/security/stock_security.xml
Labels: 14.0

#284 Merging 15.0 into 15.0.project_MI_465
  README.md
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/i18n/es_MX.po
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/readme/CONTRIBUTORS.rst
  analytic_operating_unit/readme/DESCRIPTION.rst
  analytic_operating_unit/readme/USAGE.rst
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/static/description/index.html
  analytic_operating_unit/views/analytic_account_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/analytic_operating_unit/odoo/addons/analytic_operating_unit
  setup/analytic_operating_unit/setup.py
Labels: 15.0.project_mi_465

#286 Backmerging 13.0.project_MI_465 into 13.0.project_MI_465.test
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_account_operating_unit/odoo/addons/stock_account_operating_unit
  setup/stock_account_operating_unit/setup.py
  stock_account_operating_unit/README.rst
  stock_account_operating_unit/i18n/stock_account_operating_unit.pot
  stock_account_operating_unit/model/stock_move.py
  stock_account_operating_unit/readme/CONTRIBUTORS.rst
  stock_account_operating_unit/static/description/index.html
Labels: 13.0.project_mi_465.test

#287 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  sales_team_operating_unit/README.rst
  sales_team_operating_unit/__init__.py
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/i18n/es_MX.po
  sales_team_operating_unit/i18n/sales_team_operating_unit.pot
  sales_team_operating_unit/models/__init__.py
  sales_team_operating_unit/models/crm_team.py
  sales_team_operating_unit/readme/CONTRIBUTORS.rst
  sales_team_operating_unit/readme/DESCRIPTION.rst
  sales_team_operating_unit/readme/USAGE.rst
  sales_team_operating_unit/security/crm_security.xml
  sales_team_operating_unit/static/description/icon.png
  sales_team_operating_unit/static/description/index.html
  sales_team_operating_unit/tests/__init__.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  sales_team_operating_unit/views/crm_team_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sales_team_operating_unit/odoo/addons/sales_team_operating_unit
  setup/sales_team_operating_unit/setup.py
Labels: 15.0

#288 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  account_asset_operating_unit/README.rst
  account_asset_operating_unit/__init__.py
  account_asset_operating_unit/__manifest__.py
  account_asset_operating_unit/i18n/account_asset_operating_unit.pot
  account_asset_operating_unit/models/__init__.py
  account_asset_operating_unit/models/account_asset.py
  account_asset_operating_unit/models/account_asset_line.py
  account_asset_operating_unit/models/account_move.py
  account_asset_operating_unit/readme/CONTRIBUTORS.rst
  account_asset_operating_unit/readme/DESCRIPTION.rst
  account_asset_operating_unit/readme/USAGE.rst
  account_asset_operating_unit/report/__init__.py
  account_asset_operating_unit/report/account_asset_report_xls.py
  account_asset_operating_unit/security/account_asset_security.xml
  account_asset_operating_unit/static/description/icon.png
  account_asset_operating_unit/static/description/index.html
  account_asset_operating_unit/tests/__init__.py
  account_asset_operating_unit/tests/test_account_asset_operating_unit.py
  account_asset_operating_unit/views/account_asset_views.xml
  account_asset_operating_unit/wizard/__init__.py
  account_asset_operating_unit/wizard/account_asset_remove.py
  account_asset_operating_unit/wizard/wiz_account_asset_report.py
  account_asset_operating_unit/wizard/wiz_account_asset_report.xml
  account_asset_operating_unit_access_all/README.rst
  account_asset_operating_unit_access_all/__init__.py
  account_asset_operating_unit_access_all/__manifest__.py
  account_asset_operating_unit_access_all/i18n/account_asset_operating_unit_access_all.pot
  account_asset_operating_unit_access_all/readme/CONFIGURE.rst
  account_asset_operating_unit_access_all/readme/CONTRIBUTORS.rst
  account_asset_operating_unit_access_all/readme/DESCRIPTION.rst
  account_asset_operating_unit_access_all/security/account_asset_security.xml
  account_asset_operating_unit_access_all/static/description/icon.png
  account_asset_operating_unit_access_all/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_asset_operating_unit/odoo/addons/account_asset_operating_unit
  setup/account_asset_operating_unit/setup.py
  setup/account_asset_operating_unit_access_all/odoo/addons/account_asset_operating_unit_access_all
  setup/account_asset_operating_unit_access_all/setup.py
Labels: 14.0

#290 [t126547] Adding onchange for picking type in PO so that if it change, the operating unit and requesting operating unit are changed accordingly
  purchase_operating_unit/models/purchase_order.py
Labels: enhancement, 13.0.project_mi_465.test

#281 [t126579] Added helpdesk_operating_unit module to handle OU in tickets.
  helpdesk_operating_unit/README.rst
  helpdesk_operating_unit/__init__.py
  helpdesk_operating_unit/__manifest__.py
  helpdesk_operating_unit/models/__init__.py
  helpdesk_operating_unit/models/helpdesk_ticket.py
  helpdesk_operating_unit/readme/DESCRIPTION.rst
  helpdesk_operating_unit/security/ir_rule.xml
  helpdesk_operating_unit/static/description/index.html
  helpdesk_operating_unit/views/helpdesk_ticket.xml
Labels: 13.0.project_mi_465

#291 Syncing from upstream OCA/operating-unit (12.0)
  stock_operating_unit/i18n/it.po
Labels: 12.0

#292 Syncing from upstream OCA/operating-unit (14.0)
  account_operating_unit/i18n/it.po
  operating_unit/i18n/it.po
  purchase_operating_unit/i18n/it.po
  stock_operating_unit/i18n/it.po
Labels: 14.0
