Repository brain-tec/operating-unit, pull requests merged in 2022-09, with the labels that each got.

#361 [t128046] fix return
  product_operating_unit/models/product_template.py
Labels: 15.0.project_GE_578

#363 [t128046] multicompany related problems
  operating_unit/models/res_users.py
Labels: 15.0.project_GE_578

#364 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  operating_unit/__manifest__.py
  operating_unit/models/res_users.py
  operating_unit/tests/test_operating_unit.py
Labels: 14.0

#365 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  operating_unit/__manifest__.py
  operating_unit/models/res_users.py
  operating_unit/tests/test_operating_unit.py
Labels: 15.0

#367 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  contract_operating_unit/__manifest__.py
  contract_operating_unit/views/contract_view.xml
Labels: 14.0
