Repository brain-tec/operating-unit, pull requests merged in 2022-02, with the labels that each got.

#295 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  account_asset_operating_unit/__manifest__.py
  account_asset_operating_unit/wizard/account_asset_remove.py
Labels: 14.0

#289 [t126547] Adding onchange for picking type in PO so that if it change…
  purchase_operating_unit/models/purchase_order.py
Labels: enhancement, 13.0.project_mi_465

#297 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  hr_operating_unit/__manifest__.py
  hr_operating_unit/i18n/es.po
  hr_operating_unit/i18n/hr_operating_unit.pot
  hr_operating_unit/models/__init__.py
  hr_operating_unit/models/hr_employee_base.py
Labels: 14.0

#298 Syncing from upstream OCA/operating-unit (13.0)
  operating_unit/i18n/es.po
Labels: 13.0
