Repository brain-tec/operating-unit, pull requests merged in 2022-06, with the labels that each got.

#324 Syncing from upstream OCA/operating-unit (13.0)
  stock_operating_unit/i18n/es.po
Labels: 13.0

#328 Updating travis.yml to add swig
  .travis.yml
Labels: 13.0.project_mi_465

#327 Updating from latest OCA 13.0
  stock_operating_unit/i18n/es.po
Labels: 13.0.project_mi_465

#329 Back-merge from 13.0.project_MI_465 into 13.0.project_MI_465.test
  .travis.yml
  stock_operating_unit/i18n/es.po
Labels: 13.0.project_mi_465.test, back-merge

#335 [t130202] 15 mig crm operating unit
  crm_operating_unit/README.rst
  crm_operating_unit/__init__.py
  crm_operating_unit/__manifest__.py
  crm_operating_unit/i18n/crm_operating_unit.pot
  crm_operating_unit/i18n/es.po
  crm_operating_unit/i18n/es_MX.po
  crm_operating_unit/models/__init__.py
  crm_operating_unit/models/crm_lead.py
  crm_operating_unit/readme/CONTRIBUTORS.rst
  crm_operating_unit/readme/DESCRIPTION.rst
  crm_operating_unit/readme/USAGE.rst
  crm_operating_unit/security/crm_security.xml
  crm_operating_unit/static/description/icon.png
  crm_operating_unit/static/description/index.html
  crm_operating_unit/tests/__init__.py
  crm_operating_unit/tests/test_crm_operating_unit.py
  crm_operating_unit/views/crm_lead_view.xml
Labels: 15.0.project_mi_465.t130202

#337 [t130202] 15.0 mig stock operating unit
  setup/stock_operating_unit/odoo/addons/stock_operating_unit
  setup/stock_operating_unit/setup.py
  stock_operating_unit/README.rst
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/data/stock_data.xml
  stock_operating_unit/demo/stock_demo.xml
  stock_operating_unit/hooks.py
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/migrations/15.0.1.0.0/pre-migration.py
  stock_operating_unit/model/__init__.py
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_move.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_quant.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/readme/CONFIGURE.rst
  stock_operating_unit/readme/CONTRIBUTORS.rst
  stock_operating_unit/readme/DESCRIPTION.rst
  stock_operating_unit/readme/ROADMAP.rst
  stock_operating_unit/readme/USAGE.rst
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/index.html
  stock_operating_unit/tests/__init__.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
  stock_operating_unit/view/stock.xml
Labels: 15.0.project_mi_465.t130202

#338 [t130087]15.0 mig sale operating unit
  sale_operating_unit/README.rst
  sale_operating_unit/__init__.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/i18n/es.po
  sale_operating_unit/i18n/sale_operating_unit.pot
  sale_operating_unit/models/__init__.py
  sale_operating_unit/models/crm_team.py
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/readme/CONTRIBUTORS.rst
  sale_operating_unit/readme/DESCRIPTION.rst
  sale_operating_unit/readme/USAGE.rst
  sale_operating_unit/report/__init__.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/security/sale_security.xml
  sale_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/index.html
  sale_operating_unit/test-requirements.txt
  sale_operating_unit/tests/__init__.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_operating_unit/views/sale_report_view.xml
  sale_operating_unit/views/sale_view.xml
  sale_operating_unit/wizard/__init__.py
  sale_operating_unit/wizard/sale_make_invoice_advance.py
  setup/sale_operating_unit/odoo/addons/sale_operating_unit
  setup/sale_operating_unit/setup.py
Labels: 15.0.project_mi_465.t130087

#339 15.0 mig sale stock operating unit
  sale_stock_operating_unit/README.rst
  sale_stock_operating_unit/__init__.py
  sale_stock_operating_unit/__manifest__.py
  sale_stock_operating_unit/i18n/it.po
  sale_stock_operating_unit/i18n/pt.po
  sale_stock_operating_unit/i18n/sale_stock_operating_unit.pot
  sale_stock_operating_unit/models/__init__.py
  sale_stock_operating_unit/models/sale_order.py
  sale_stock_operating_unit/models/stock_move.py
  sale_stock_operating_unit/models/stock_warehouse.py
  sale_stock_operating_unit/readme/CONFIGURATION.rst
  sale_stock_operating_unit/readme/CONTRIBUTORS.rst
  sale_stock_operating_unit/readme/DESCRIPTION.rst
  sale_stock_operating_unit/readme/USAGE.rst
  sale_stock_operating_unit/static/description/icon.png
  sale_stock_operating_unit/static/description/index.html
  sale_stock_operating_unit/test-requirements.txt
  sale_stock_operating_unit/tests/__init__.py
  sale_stock_operating_unit/tests/test_sale_stock_operating_unit.py
  setup/sale_stock_operating_unit/odoo/addons/sale_stock_operating_unit
  setup/sale_stock_operating_unit/setup.py
Labels: 15.0.project_mi_465.t130087

#340 [130087]15.0 mig stock account operating unit
  setup/stock_account_operating_unit/odoo/addons/stock_account_operating_unit
  setup/stock_account_operating_unit/setup.py
  stock_account_operating_unit/README.rst
  stock_account_operating_unit/__init__.py
  stock_account_operating_unit/__manifest__.py
  stock_account_operating_unit/i18n/es.po
  stock_account_operating_unit/i18n/stock_account_operating_unit.pot
  stock_account_operating_unit/model/__init__.py
  stock_account_operating_unit/model/stock_move.py
  stock_account_operating_unit/readme/CONFIGURATION.rst
  stock_account_operating_unit/readme/CONTRIBUTORS.rst
  stock_account_operating_unit/readme/DESCRIPTION.rst
  stock_account_operating_unit/readme/USAGE.rst
  stock_account_operating_unit/static/description/icon.png
  stock_account_operating_unit/static/description/index.html
  stock_account_operating_unit/test-requirements.txt
  stock_account_operating_unit/tests/__init__.py
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
Labels: 15.0.project_mi_465.t130087

#342 [t130087] 15.0 mig account operating unit
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/models/__init__.py
  account_operating_unit/models/account_journal.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_payment.py
  account_operating_unit/models/res_company.py
  account_operating_unit/readme/CONFIGURE.rst
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/readme/DESCRIPTION.rst
  account_operating_unit/readme/ROADMAP.rst
  account_operating_unit/readme/USAGE.rst
  account_operating_unit/report/__init__.py
  account_operating_unit/report/account_invoice_report.py
  account_operating_unit/security/account_security.xml
  account_operating_unit/static/description/icon.png
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/__init__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/views/account_invoice_report_view.xml
  account_operating_unit/views/account_journal_view.xml
  account_operating_unit/views/account_move_view.xml
  account_operating_unit/views/account_payment_view.xml
  account_operating_unit/views/company_view.xml
  account_operating_unit/wizards/__init__.py
  account_operating_unit/wizards/account_payment_register.py
  setup/account_operating_unit/odoo/addons/account_operating_unit
  setup/account_operating_unit/setup.py
Labels: 15.0.project_mi_465.t130087

#344 [t130203]15.0 mig mrp operating unit
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/readme/CONTRIBUTORS.rst
  mrp_operating_unit/readme/DESCRIPTION.rst
  mrp_operating_unit/readme/USAGE.rst
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
  setup/mrp_operating_unit/odoo/addons/mrp_operating_unit
  setup/mrp_operating_unit/setup.py
Labels: 15.0.project_mi_465.t130203

#346 Syncing from upstream OCA/operating-unit (14.0)
  agreement_operating_unit/i18n/fr.po
  crm_operating_unit/i18n/fr.po
  fieldservice_operating_unit/i18n/fr.po
  hr_operating_unit/i18n/fr.po
  operating_unit/i18n/fr.po
  purchase_request_operating_unit/i18n/fr.po
Labels: 14.0

#347 [t127490][15.0][MIG] Migration of module stock_operating_unit
  setup/stock_operating_unit/odoo/addons/stock_operating_unit
  setup/stock_operating_unit/setup.py
  stock_operating_unit/README.rst
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/data/stock_data.xml
  stock_operating_unit/demo/stock_demo.xml
  stock_operating_unit/hooks.py
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/migrations/15.0.1.0.0/pre-migration.py
  stock_operating_unit/model/__init__.py
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_move.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_quant.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/readme/CONFIGURE.rst
  stock_operating_unit/readme/CONTRIBUTORS.rst
  stock_operating_unit/readme/DESCRIPTION.rst
  stock_operating_unit/readme/ROADMAP.rst
  stock_operating_unit/readme/USAGE.rst
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/index.html
  stock_operating_unit/tests/__init__.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
  stock_operating_unit/view/stock.xml
Labels: 15.0.project_sv_559

#348 [t127490][15.0][MIG] Migration of module mrp_operating_unit
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/readme/CONTRIBUTORS.rst
  mrp_operating_unit/readme/DESCRIPTION.rst
  mrp_operating_unit/readme/USAGE.rst
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
  setup/mrp_operating_unit/odoo/addons/mrp_operating_unit
  setup/mrp_operating_unit/setup.py
Labels: 15.0.project_sv_559
