Repository brain-tec/operating-unit, pull requests merged in 2022-03, with the labels that each got.

#300 [t126579] Revert helpdesk_operating_unit, as it depends on helpdesk that is an enterprise module
  helpdesk_operating_unit/README.rst
  helpdesk_operating_unit/__init__.py
  helpdesk_operating_unit/__manifest__.py
  helpdesk_operating_unit/models/__init__.py
  helpdesk_operating_unit/models/helpdesk_ticket.py
  helpdesk_operating_unit/readme/DESCRIPTION.rst
  helpdesk_operating_unit/security/ir_rule.xml
  helpdesk_operating_unit/static/description/index.html
  helpdesk_operating_unit/views/helpdesk_ticket.xml
Labels: 13.0.project_mi_465

#299 Updating from latest OCA 13.0
  operating_unit/i18n/es.po
Labels: 13.0.project_mi_465

#301 Back-merge from 13.0.project_MI_465 into 13.0.project_MI_465.test
  helpdesk_operating_unit/README.rst
  helpdesk_operating_unit/__init__.py
  helpdesk_operating_unit/__manifest__.py
  helpdesk_operating_unit/models/__init__.py
  helpdesk_operating_unit/models/helpdesk_ticket.py
  helpdesk_operating_unit/readme/DESCRIPTION.rst
  helpdesk_operating_unit/security/ir_rule.xml
  helpdesk_operating_unit/static/description/index.html
  helpdesk_operating_unit/views/helpdesk_ticket.xml
  operating_unit/i18n/es.po
Labels: 13.0.project_mi_465.test, back-merge

#302 Syncing from upstream OCA/operating-unit (14.0)
  operating_unit/i18n/es_CL.po
  operating_unit/i18n/es_DO.po
Labels: 14.0

#303 Syncing from upstream OCA/operating-unit (13.0)
  account_operating_unit/i18n/es.po
  operating_unit/i18n/es.po
  purchase_operating_unit/i18n/es.po
  purchase_operating_unit/i18n/es_PA.po
  sale_operating_unit/i18n/es.po
  stock_account_operating_unit/i18n/es.po
Labels: 13.0

#304 Syncing from upstream OCA/operating-unit (13.0)
  hr_expense_operating_unit/README.rst
  hr_expense_operating_unit/__manifest__.py
  hr_expense_operating_unit/i18n/hr_expense_operating_unit.pot
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit/static/description/index.html
Labels: 13.0

#305 Backmerging 13.0.project_MI_465 into 13.0
  account_operating_unit/i18n/es.po
  hr_expense_operating_unit/README.rst
  hr_expense_operating_unit/__manifest__.py
  hr_expense_operating_unit/i18n/hr_expense_operating_unit.pot
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit/static/description/index.html
  operating_unit/i18n/es.po
  purchase_operating_unit/i18n/es.po
  purchase_operating_unit/i18n/es_PA.po
  sale_operating_unit/i18n/es.po
  stock_account_operating_unit/i18n/es.po
Labels: 13.0.project_mi_465

#306 Backmerging 13.0.project_MI_465.test and 13.0.project_MI_465
  account_operating_unit/i18n/es.po
  hr_expense_operating_unit/README.rst
  hr_expense_operating_unit/__manifest__.py
  hr_expense_operating_unit/i18n/hr_expense_operating_unit.pot
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit/static/description/index.html
  operating_unit/i18n/es.po
  purchase_operating_unit/i18n/es.po
  purchase_operating_unit/i18n/es_PA.po
  sale_operating_unit/i18n/es.po
  stock_account_operating_unit/i18n/es.po
Labels: 13.0.project_mi_465.test
