Repository brain-tec/operating-unit, pull requests merged in 2023-07, with the labels that each got.

#474 Syncing from upstream OCA/operating-unit (12.0)
  product_operating_unit/i18n/it.po
Labels: 12.0

#475 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  hr_contract_operating_unit/i18n/hr_contract_operating_unit.pot
  hr_contract_operating_unit/i18n/pt.po
  hr_payroll_account_operating_unit/README.rst
  hr_payroll_account_operating_unit/__init__.py
  hr_payroll_account_operating_unit/__manifest__.py
  hr_payroll_account_operating_unit/i18n/hr_payroll_account_operating_unit.pot
  hr_payroll_account_operating_unit/i18n/pt.po
  hr_payroll_account_operating_unit/models/__init__.py
  hr_payroll_account_operating_unit/models/account_move.py
  hr_payroll_account_operating_unit/models/hr_payslip.py
  hr_payroll_account_operating_unit/readme/CONTRIBUTORS.rst
  hr_payroll_account_operating_unit/readme/DESCRIPTION.rst
  hr_payroll_account_operating_unit/static/description/icon.png
  hr_payroll_account_operating_unit/static/description/index.html
  hr_payroll_account_operating_unit/tests/__init__.py
  hr_payroll_account_operating_unit/tests/test_payroll_account_operating_unit.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_payroll_account_operating_unit/odoo/addons/hr_payroll_account_operating_unit
  setup/hr_payroll_account_operating_unit/setup.py
Labels: 15.0

#476 [16.0][MIG] account_operating_unit
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/i18n/es_MX.po
  account_operating_unit/models/__init__.py
  account_operating_unit/models/account_bank_statement.py
  account_operating_unit/models/account_journal.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_partial_reconcile.py
  account_operating_unit/models/account_payment.py
  account_operating_unit/models/res_company.py
  account_operating_unit/readme/CONFIGURE.rst
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/readme/DESCRIPTION.rst
  account_operating_unit/readme/ROADMAP.rst
  account_operating_unit/readme/USAGE.rst
  account_operating_unit/report/__init__.py
  account_operating_unit/report/account_invoice_report.py
  account_operating_unit/security/account_security.xml
  account_operating_unit/static/description/icon.png
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/__init__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/views/account_invoice_report_view.xml
  account_operating_unit/views/account_journal_view.xml
  account_operating_unit/views/account_move_view.xml
  account_operating_unit/views/account_payment_view.xml
  account_operating_unit/views/company_view.xml
  account_operating_unit/wizards/__init__.py
  account_operating_unit/wizards/account_payment_register.py
  setup/account_operating_unit/odoo/addons/account_operating_unit
  setup/account_operating_unit/setup.py
Labels: 16.0.project_sa_690

#478 [16.0][MIG] purchase_operating_unit
  purchase_operating_unit/README.rst
  purchase_operating_unit/__init__.py
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/demo/purchase_order_demo.xml
  purchase_operating_unit/i18n/purchase_operating_unit.pot
  purchase_operating_unit/models/__init__.py
  purchase_operating_unit/models/account_move.py
  purchase_operating_unit/models/purchase_order.py
  purchase_operating_unit/readme/CONTRIBUTORS.rst
  purchase_operating_unit/readme/DESCRIPTION.rst
  purchase_operating_unit/readme/USAGE.rst
  purchase_operating_unit/security/purchase_security.xml
  purchase_operating_unit/static/description/icon.png
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/tests/__init__.py
  purchase_operating_unit/tests/test_po_security.py
  purchase_operating_unit/tests/test_purchase_operating_unit.py
  purchase_operating_unit/views/purchase_order_line_view.xml
  purchase_operating_unit/views/purchase_order_view.xml
  setup/purchase_operating_unit/odoo/addons/purchase_operating_unit
  setup/purchase_operating_unit/setup.py
Labels: 16.0.project_sa_690

#477 [16.0][MIG] sale_operating_unit
  sale_operating_unit/README.rst
  sale_operating_unit/__init__.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/i18n/sale_operating_unit.pot
  sale_operating_unit/models/__init__.py
  sale_operating_unit/models/crm_team.py
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/readme/CONTRIBUTORS.rst
  sale_operating_unit/readme/DESCRIPTION.rst
  sale_operating_unit/readme/ROADMAP.rst
  sale_operating_unit/readme/USAGE.rst
  sale_operating_unit/report/__init__.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/security/sale_security.xml
  sale_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/index.html
  sale_operating_unit/tests/__init__.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_operating_unit/views/sale_report_view.xml
  sale_operating_unit/views/sale_view.xml
  sale_operating_unit/wizard/__init__.py
  sale_operating_unit/wizard/sale_make_invoice_advance.py
  setup/sale_operating_unit/odoo/addons/sale_operating_unit
  setup/sale_operating_unit/setup.py
Labels: 16.0.project_sa_690

#479 [16.0][MIG] sales_team_operating_unit
  sales_team_operating_unit/README.rst
  sales_team_operating_unit/__init__.py
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/i18n/es_AR.po
  sales_team_operating_unit/i18n/es_MX.po
  sales_team_operating_unit/i18n/sales_team_operating_unit.pot
  sales_team_operating_unit/models/__init__.py
  sales_team_operating_unit/models/crm_team.py
  sales_team_operating_unit/readme/CONTRIBUTORS.rst
  sales_team_operating_unit/readme/DESCRIPTION.rst
  sales_team_operating_unit/readme/USAGE.rst
  sales_team_operating_unit/security/crm_security.xml
  sales_team_operating_unit/static/description/icon.png
  sales_team_operating_unit/static/description/index.html
  sales_team_operating_unit/tests/__init__.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  sales_team_operating_unit/views/crm_team_view.xml
  setup/sales_team_operating_unit/odoo/addons/sales_team_operating_unit
  setup/sales_team_operating_unit/setup.py
Labels: 16.0.project_sa_690

#480 Syncing from upstream OCA/operating-unit (13.0)
  README.md
  sale_operating_unit/__manifest__.py
  sale_operating_unit/models/sale_order.py
Labels: 13.0

#481 Syncing from upstream OCA/operating-unit (14.0)
  purchase_operating_unit/i18n/it.po
Labels: 14.0

#482 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  sale_operating_unit/__manifest__.py
  sale_operating_unit/models/sale_order.py
Labels: 14.0

#483 Syncing from upstream OCA/operating-unit (14.0)
  sale_operating_unit/i18n/it.po
Labels: 14.0
