Repository brain-tec/operating-unit, pull requests merged in 2023-01, with the labels that each got.

#385 Syncing from upstream OCA/operating-unit (12.0)
  purchase_operating_unit/i18n/it.po
Labels: 12.0

#386 Syncing from upstream OCA/operating-unit (14.0)
  account_operating_unit/i18n/it.po
  analytic_operating_unit/i18n/it.po
  mis_builder_operating_unit/i18n/it.po
  purchase_operating_unit/i18n/it.po
Labels: 14.0

#387 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  operating_unit_access_all/README.rst
  operating_unit_access_all/__init__.py
  operating_unit_access_all/__manifest__.py
  operating_unit_access_all/i18n/operating_unit_access_all.pot
  operating_unit_access_all/readme/CONFIGURE.rst
  operating_unit_access_all/readme/CONTRIBUTORS.rst
  operating_unit_access_all/readme/DESCRIPTION.rst
  operating_unit_access_all/security/operating_unit_security.xml
  operating_unit_access_all/static/description/icon.png
  operating_unit_access_all/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/operating_unit_access_all/odoo/addons/operating_unit_access_all
  setup/operating_unit_access_all/setup.py
Labels: 15.0

#389 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  operating_unit/__manifest__.py
  operating_unit/models/operating_unit.py
  pos_operating_unit/README.rst
  pos_operating_unit/__init__.py
  pos_operating_unit/__manifest__.py
  pos_operating_unit/models/__init__.py
  pos_operating_unit/models/pos_config.py
  pos_operating_unit/models/pos_order.py
  pos_operating_unit/models/pos_payment.py
  pos_operating_unit/models/pos_session.py
  pos_operating_unit/readme/CONTRIBUTORS.rst
  pos_operating_unit/readme/DESCRIPTION.rst
  pos_operating_unit/readme/ROADMAP.rst
  pos_operating_unit/readme/USAGE.rst
  pos_operating_unit/security/pos_security.xml
  pos_operating_unit/static/description/icon.png
  pos_operating_unit/static/description/index.html
  pos_operating_unit/tests/__init__.py
  pos_operating_unit/tests/test_module.py
  pos_operating_unit/views/pos_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_operating_unit/odoo/addons/pos_operating_unit
  setup/pos_operating_unit/setup.py
Labels: 14.0

#391 Syncing from upstream OCA/operating-unit (14.0)
  analytic_operating_unit_access_all/i18n/it.po
Labels: 14.0

#392 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  operating_unit/__manifest__.py
  operating_unit/models/operating_unit.py
Labels: 15.0

#393 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  hr_contract_operating_unit/README.rst
  hr_contract_operating_unit/__init__.py
  hr_contract_operating_unit/__manifest__.py
  hr_contract_operating_unit/i18n/hr_contract_operating_unit.pot
  hr_contract_operating_unit/i18n/pt.po
  hr_contract_operating_unit/models/__init__.py
  hr_contract_operating_unit/models/hr_contract.py
  hr_contract_operating_unit/readme/CONTRIBUTORS.rst
  hr_contract_operating_unit/readme/DESCRIPTION.rst
  hr_contract_operating_unit/readme/USAGE.rst
  hr_contract_operating_unit/security/hr_contract_security.xml
  hr_contract_operating_unit/static/description/icon.png
  hr_contract_operating_unit/static/description/index.html
  hr_contract_operating_unit/tests/__init__.py
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  hr_contract_operating_unit/views/hr_contract_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_contract_operating_unit/odoo/addons/hr_contract_operating_unit
  setup/hr_contract_operating_unit/setup.py
Labels: 15.0

#394 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  operating_unit/__manifest__.py
  operating_unit/models/res_users.py
Labels: 14.0

#395 Syncing from upstream OCA/operating-unit (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  account_operating_unit_access_all/i18n/account_operating_unit_access_all.pot
  contract_operating_unit/i18n/contract_operating_unit.pot
  contract_operating_unit_access_all/i18n/contract_operating_unit_access_all.pot
  hr_contract_operating_unit/i18n/hr_contract_operating_unit.pot
  hr_contract_operating_unit/i18n/pt.po
  hr_payroll_account_operating_unit/i18n/hr_payroll_account_operating_unit.pot
  hr_payroll_account_operating_unit/i18n/pt.po
  mail_template_operating_unit/i18n/mail_template_operating_unit.pot
  mis_builder_operating_unit_access_all/i18n/mis_builder_operating_unit_access_all.pot
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_CL.po
  operating_unit/i18n/es_DO.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/fr.po
  operating_unit/i18n/it.po
  operating_unit/i18n/operating_unit.pot
  pos_operating_unit/i18n/pos_operating_unit.pot
  project_operating_unit/i18n/project_operating_unit.pot
  project_operating_unit/i18n/pt.po
  purchase_request_to_requisition_operating_unit/i18n/purchase_request_to_requisition_operating_unit.pot
  report_qweb_operating_unit/i18n/es_MX.po
  report_qweb_operating_unit/i18n/report_qweb_operating_unit.pot
  sale_operating_unit/i18n/sale_operating_unit.pot
  sale_template_operating_unit/i18n/sale_template_operating_unit.pot
Labels: 14.0

#396 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  operating_unit/__manifest__.py
  operating_unit/models/res_users.py
Labels: 15.0

#397 Syncing from upstream OCA/operating-unit (12.0)
  operating_unit/i18n/it.po
  product_operating_unit/i18n/it.po
  res_partner_operating_unit/i18n/it.po
  sale_multi_operating_unit/i18n/it.po
  sale_stock_operating_unit/i18n/it.po
  stock_operating_unit/i18n/it.po
Labels: 12.0

#398 Syncing from upstream OCA/operating-unit (14.0)
  account_operating_unit/i18n/it.po
  analytic_operating_unit/i18n/it.po
  mis_builder_operating_unit/i18n/it.po
  operating_unit/i18n/it.po
  pos_operating_unit/i18n/it.po
  stock_operating_unit/i18n/it.po
Labels: 14.0

#399 [t132190] Fixed warnings appearing due to incomplete migration
  crm_operating_unit/models/crm_lead.py
Labels: 15.0.project_mi_465

#400 [t134232][MIG] Migration of hr_expense_operating_unit
  hr_expense_operating_unit/README.rst
  hr_expense_operating_unit/__init__.py
  hr_expense_operating_unit/__manifest__.py
  hr_expense_operating_unit/i18n/hr_expense_operating_unit.pot
  hr_expense_operating_unit/models/__init__.py
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit/readme/DESCRIPTION.rst
  hr_expense_operating_unit/readme/USAGE.rst
  hr_expense_operating_unit/security/hr_expense_security.xml
  hr_expense_operating_unit/static/description/icon.png
  hr_expense_operating_unit/static/description/index.html
  hr_expense_operating_unit/tests/__init__.py
  hr_expense_operating_unit/tests/test_hr_expense_operating_unit.py
  hr_expense_operating_unit/views/hr_expense_view.xml
Labels: 15.0.project_mi_465

#401 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  crm_operating_unit/README.rst
  crm_operating_unit/__init__.py
  crm_operating_unit/__manifest__.py
  crm_operating_unit/i18n/crm_operating_unit.pot
  crm_operating_unit/i18n/es.po
  crm_operating_unit/i18n/es_MX.po
  crm_operating_unit/i18n/fr.po
  crm_operating_unit/models/__init__.py
  crm_operating_unit/models/crm_lead.py
  crm_operating_unit/readme/CONTRIBUTORS.rst
  crm_operating_unit/readme/DESCRIPTION.rst
  crm_operating_unit/readme/USAGE.rst
  crm_operating_unit/security/crm_security.xml
  crm_operating_unit/static/description/icon.png
  crm_operating_unit/static/description/index.html
  crm_operating_unit/tests/__init__.py
  crm_operating_unit/tests/test_crm_operating_unit.py
  crm_operating_unit/views/crm_lead_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/crm_operating_unit/odoo/addons/crm_operating_unit
  setup/crm_operating_unit/setup.py
Labels: 15.0

#402 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__manifest__.py
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/static/description/index.html
  account_operating_unit/wizards/account_payment_register.py
Labels: 15.0

#403 Syncing from upstream OCA/operating-unit (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/models/account_analytic_account.py
  hr_contract_operating_unit/__manifest__.py
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  mis_builder_budget_operating_unit/README.rst
  mis_builder_budget_operating_unit/__manifest__.py
  mis_builder_budget_operating_unit/models/mis_budget_item.py
  mis_builder_budget_operating_unit/static/description/index.html
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/static/description/index.html
  mis_builder_operating_unit/tests/__init__.py
  mis_builder_operating_unit/tests/test_mis_builder_operating_unit.py
  mrp_operating_unit/__manifest__.py
  operating_unit/README.rst
  operating_unit/__manifest__.py
  operating_unit/i18n/es.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/static/description/index.html
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/res_users_view.xml
  report_qweb_operating_unit/__manifest__.py
Labels: 13.0

#404 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/models/account_analytic_account.py
  operating_unit/__manifest__.py
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/tests/test_operating_unit.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/report/sale_report.py
Labels: 14.0

#405 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/models/account_analytic_account.py
  hr_contract_operating_unit/__manifest__.py
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  operating_unit/__manifest__.py
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/tests/test_operating_unit.py
Labels: 15.0
