Repository brain-tec/operating-unit, pull requests merged in 2023-05, with the labels that each got.

#441 [16.0] [MIG] analytic_operating_unit
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/i18n/es_AR.po
  analytic_operating_unit/i18n/es_MX.po
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/readme/CONTRIBUTORS.rst
  analytic_operating_unit/readme/DESCRIPTION.rst
  analytic_operating_unit/readme/USAGE.rst
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/static/description/index.html
  analytic_operating_unit/views/analytic_account_view.xml
  setup/analytic_operating_unit/odoo/addons/analytic_operating_unit
  setup/analytic_operating_unit/setup.py
Labels: 16.0.project_ba_688

#443 Syncing from upstream OCA/operating-unit (12.0)
  stock_operating_unit/i18n/it.po
Labels: 12.0

#444 Syncing from upstream OCA/operating-unit (14.0)
  stock_operating_unit/i18n/it.po
Labels: 14.0

#445 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  account_operating_unit/__manifest__.py
  account_operating_unit/wizards/account_payment_register.py
Labels: 15.0

#440 [16.0][MIG] account_operating_unit
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/i18n/es_MX.po
  account_operating_unit/models/__init__.py
  account_operating_unit/models/account_bank_statement.py
  account_operating_unit/models/account_journal.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_partial_reconcile.py
  account_operating_unit/models/account_payment.py
  account_operating_unit/models/res_company.py
  account_operating_unit/readme/CONFIGURE.rst
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/readme/DESCRIPTION.rst
  account_operating_unit/readme/ROADMAP.rst
  account_operating_unit/readme/USAGE.rst
  account_operating_unit/report/__init__.py
  account_operating_unit/report/account_invoice_report.py
  account_operating_unit/security/account_security.xml
  account_operating_unit/static/description/icon.png
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/__init__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/views/account_invoice_report_view.xml
  account_operating_unit/views/account_journal_view.xml
  account_operating_unit/views/account_move_view.xml
  account_operating_unit/views/account_payment_view.xml
  account_operating_unit/views/company_view.xml
  account_operating_unit/wizards/__init__.py
  account_operating_unit/wizards/account_payment_register.py
  setup/account_operating_unit/odoo/addons/account_operating_unit
  setup/account_operating_unit/setup.py
Labels: 16.0.project_ba_688

#442 [16.0][MIG] purchase_operating_unit
  purchase_operating_unit/README.rst
  purchase_operating_unit/__init__.py
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/demo/purchase_order_demo.xml
  purchase_operating_unit/i18n/purchase_operating_unit.pot
  purchase_operating_unit/models/__init__.py
  purchase_operating_unit/models/account_move.py
  purchase_operating_unit/models/purchase_order.py
  purchase_operating_unit/readme/CONTRIBUTORS.rst
  purchase_operating_unit/readme/DESCRIPTION.rst
  purchase_operating_unit/readme/USAGE.rst
  purchase_operating_unit/security/purchase_security.xml
  purchase_operating_unit/static/description/icon.png
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/tests/__init__.py
  purchase_operating_unit/tests/test_po_security.py
  purchase_operating_unit/tests/test_purchase_operating_unit.py
  purchase_operating_unit/views/purchase_order_line_view.xml
  purchase_operating_unit/views/purchase_order_view.xml
  setup/purchase_operating_unit/odoo/addons/purchase_operating_unit
  setup/purchase_operating_unit/setup.py
Labels: 16.0.project_ba_688

#451 Syncing from upstream OCA/operating-unit (12.0)
  sale_multi_operating_unit/i18n/it.po
Labels: 12.0

#452 [16.0][MIG] sale_operating_unit: Migration to 16.0
  sale_operating_unit/README.rst
  sale_operating_unit/__init__.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/i18n/sale_operating_unit.pot
  sale_operating_unit/models/__init__.py
  sale_operating_unit/models/crm_team.py
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/readme/CONTRIBUTORS.rst
  sale_operating_unit/readme/DESCRIPTION.rst
  sale_operating_unit/readme/ROADMAP.rst
  sale_operating_unit/readme/USAGE.rst
  sale_operating_unit/report/__init__.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/security/sale_security.xml
  sale_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/index.html
  sale_operating_unit/tests/__init__.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_operating_unit/views/sale_report_view.xml
  sale_operating_unit/views/sale_view.xml
  sale_operating_unit/wizard/__init__.py
  sale_operating_unit/wizard/sale_make_invoice_advance.py
  setup/sale_operating_unit/odoo/addons/sale_operating_unit
  setup/sale_operating_unit/setup.py
Labels: 16.0.project_ba_688

#454 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  hr_expense_operating_unit_access_all/README.rst
  hr_expense_operating_unit_access_all/__init__.py
  hr_expense_operating_unit_access_all/__manifest__.py
  hr_expense_operating_unit_access_all/i18n/hr_expense_operating_unit_access_all.pot
  hr_expense_operating_unit_access_all/readme/CONFIGURE.rst
  hr_expense_operating_unit_access_all/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit_access_all/readme/DESCRIPTION.rst
  hr_expense_operating_unit_access_all/security/hr_expense_security.xml
  hr_expense_operating_unit_access_all/static/description/icon.png
  hr_expense_operating_unit_access_all/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_expense_operating_unit_access_all/odoo/addons/hr_expense_operating_unit_access_all
  setup/hr_expense_operating_unit_access_all/setup.py
  setup/stock_operating_unit_access_all/odoo/addons/stock_operating_unit_access_all
  setup/stock_operating_unit_access_all/setup.py
  stock_operating_unit_access_all/README.rst
  stock_operating_unit_access_all/__init__.py
  stock_operating_unit_access_all/__manifest__.py
  stock_operating_unit_access_all/i18n/stock_operating_unit_access_all.pot
  stock_operating_unit_access_all/readme/CONFIGURE.rst
  stock_operating_unit_access_all/readme/CONTRIBUTORS.rst
  stock_operating_unit_access_all/readme/DESCRIPTION.rst
  stock_operating_unit_access_all/security/stock_security.xml
  stock_operating_unit_access_all/static/description/icon.png
  stock_operating_unit_access_all/static/description/index.html
Labels: 15.0

#457 Syncing from upstream OCA/operating-unit (15.0)
  stock_operating_unit/migrations/15.0.1.0.0/pre-migration.py
Labels: 15.0

#458 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/i18n/da.po
  mis_builder_operating_unit/i18n/it.po
  mis_builder_operating_unit/i18n/mis_builder_operating_unit.pot
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_operating_unit/readme/DESCRIPTION.rst
  mis_builder_operating_unit/readme/USAGE.rst
  mis_builder_operating_unit/security/mis_builder_security.xml
  mis_builder_operating_unit/static/description/icon.png
  mis_builder_operating_unit/static/description/index.html
  mis_builder_operating_unit/view/mis_builder.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mis_builder_operating_unit/odoo/addons/mis_builder_operating_unit
  setup/mis_builder_operating_unit/setup.py
Labels: 15.0
