Repository brain-tec/operating-unit, pull requests merged in 2023-12, with the labels that each got.

#491 [t140228] [NORAM15] [DEV] Migration v15 - Operating Unit
  product_operating_unit/README.rst
  product_operating_unit/__init__.py
  product_operating_unit/__manifest__.py
  product_operating_unit/i18n/product_operating_unit.pot
  product_operating_unit/models/__init__.py
  product_operating_unit/models/product_category.py
  product_operating_unit/models/product_template.py
  product_operating_unit/readme/CONTRIBUTORS.rst
  product_operating_unit/readme/DESCRIPTION.rst
  product_operating_unit/readme/ROADMAP.rst
  product_operating_unit/readme/USAGE.rst
  product_operating_unit/security/product_template_security.xml
  product_operating_unit/static/description/icon.png
  product_operating_unit/static/description/index.html
  product_operating_unit/tests/__init__.py
  product_operating_unit/tests/test_product_operating_unit.py
  product_operating_unit/views/product_category_view.xml
  product_operating_unit/views/product_template_view.xml
  stock_operating_unit_product_operating_unit/LICENSE
  stock_operating_unit_product_operating_unit/README.rst
  stock_operating_unit_product_operating_unit/__init__.py
  stock_operating_unit_product_operating_unit/__manifest__.py
  stock_operating_unit_product_operating_unit/readme/CONFIGURE.rst
  stock_operating_unit_product_operating_unit/readme/CONTRIBUTORS.rst
  stock_operating_unit_product_operating_unit/readme/DESCRIPTION.rst
  stock_operating_unit_product_operating_unit/security/stock_security.xml
  stock_operating_unit_product_operating_unit/static/description/icon.png
  stock_operating_unit_product_operating_unit/static/description/index.html
Labels: 15.0.project_mi_465

#429 [t136510] [NORAM15] [DEV] Migration v15 - MIUS Accounting & Expenses
  mail_operating_unit/LICENSE
  mail_operating_unit/README.rst
  mail_operating_unit/__init__.py
  mail_operating_unit/__manifest__.py
  mail_operating_unit/data/mail_data.xml
  mail_operating_unit/models/__init__.py
  mail_operating_unit/models/mail_alias.py
  mail_operating_unit/models/mail_mail.py
  mail_operating_unit/models/mail_template.py
  mail_operating_unit/models/operating_unit.py
  mail_operating_unit/models/res_users.py
  mail_operating_unit/readme/CONTRIBUTORS.rst
  mail_operating_unit/readme/DESCRIPTION.rst
  mail_operating_unit/readme/ROADMAP.rst
  mail_operating_unit/readme/USAGE.rst
  mail_operating_unit/security/ir.model.access.csv
  mail_operating_unit/security/mail_alias_security.xml
  mail_operating_unit/security/mail_template_security.xml
  mail_operating_unit/static/description/icon.png
  mail_operating_unit/static/description/index.html
  mail_operating_unit/views/mail_alias_views.xml
  mail_operating_unit/views/mail_template_views.xml
  mail_operating_unit/views/operating_unit_views.xml
  mail_operating_unit/views/res_users_view.xml
  mail_operating_unit/wizard/__init__.py
  mail_operating_unit/wizard/mail_compose_message.py
  mail_operating_unit/wizard/mail_compose_message_view.xml
Labels: 15.0.project_mi_465

#531 Syncing from upstream OCA/operating-unit (12.0)
  stock_operating_unit/i18n/it.po
Labels: 12.0

#532 Syncing from upstream OCA/operating-unit (14.0)
  stock_operating_unit/i18n/it.po
Labels: 14.0
