Repository brain-tec/operating-unit, pull requests merged in 2023-02, with the labels that each got.

#409 Syncing from upstream OCA/operating-unit (12.0)
  operating_unit/i18n/it.po
Labels: 12.0

#410 [t134615] Moved missing changes from 13.0.project_MI_465 into 15.0.project_MI_465
  .braintec/deploy.yaml
  hr_expense_operating_unit/__init__.py
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/tests/test_hr_expense_operating_unit.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/res_users.py
  operating_unit/tests/OperatingUnitsTransactionCase.py
  operating_unit/tests/__init__.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/res_users_view.xml
  purchase_operating_unit/tests/test_purchase_operating_unit.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_stock_operating_unit/tests/test_sale_stock_operating_unit.py
  setup/hr_expense_operating_unit/odoo/addons/hr_expense_operating_unit
  setup/hr_expense_operating_unit/setup.py
Labels: 15.0.project_mi_465

#413 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_account_operating_unit/odoo/addons/stock_account_operating_unit
  setup/stock_account_operating_unit/setup.py
  stock_account_operating_unit/README.rst
  stock_account_operating_unit/__init__.py
  stock_account_operating_unit/__manifest__.py
  stock_account_operating_unit/i18n/es.po
  stock_account_operating_unit/i18n/stock_account_operating_unit.pot
  stock_account_operating_unit/model/__init__.py
  stock_account_operating_unit/model/stock_move.py
  stock_account_operating_unit/readme/CONFIGURATION.rst
  stock_account_operating_unit/readme/CONTRIBUTORS.rst
  stock_account_operating_unit/readme/DESCRIPTION.rst
  stock_account_operating_unit/readme/USAGE.rst
  stock_account_operating_unit/static/description/icon.png
  stock_account_operating_unit/static/description/index.html
  stock_account_operating_unit/test-requirements.txt
  stock_account_operating_unit/tests/__init__.py
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
Labels: 15.0

#414 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  sale_crm_operating_unit/README.rst
  sale_crm_operating_unit/__init__.py
  sale_crm_operating_unit/__manifest__.py
  sale_crm_operating_unit/i18n/sale_crm_operating_unit.pot
  sale_crm_operating_unit/models/__init__.py
  sale_crm_operating_unit/models/crm_lead.py
  sale_crm_operating_unit/models/sale.py
  sale_crm_operating_unit/readme/CONTRIBUTORS.rst
  sale_crm_operating_unit/readme/DESCRIPTION.rst
  sale_crm_operating_unit/static/description/icon.png
  sale_crm_operating_unit/static/description/index.html
  sale_crm_operating_unit/tests/__init__.py
  sale_crm_operating_unit/tests/test_sale_crm_operating_unit.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_crm_operating_unit/odoo/addons/sale_crm_operating_unit
  setup/sale_crm_operating_unit/setup.py
Labels: 14.0

#415 Syncing from upstream OCA/operating-unit (12.0)
  purchase_operating_unit/i18n/it.po
Labels: 12.0

#416 [t134190][WIP] Changes to premigration script of stock operating unit, location_id seems to be ambiguous
  stock_operating_unit/migrations/15.0.1.0.0/pre-migration.py
Labels: 15.0.project_mi_465
