Repository brain-tec/operating-unit, pull requests merged in 2024-12, with the labels that each got.

#616 Syncing from upstream OCA/operating-unit (17.0)
  README.md
  report_qweb_operating_unit/README.rst
  report_qweb_operating_unit/__init__.py
  report_qweb_operating_unit/__manifest__.py
  report_qweb_operating_unit/i18n/es_MX.po
  report_qweb_operating_unit/i18n/report_qweb_operating_unit.pot
  report_qweb_operating_unit/models/__init__.py
  report_qweb_operating_unit/models/operating_unit.py
  report_qweb_operating_unit/pyproject.toml
  report_qweb_operating_unit/readme/CONTRIBUTORS.md
  report_qweb_operating_unit/readme/DESCRIPTION.md
  report_qweb_operating_unit/static/description/icon.png
  report_qweb_operating_unit/static/description/index.html
  report_qweb_operating_unit/tests/__init__.py
  report_qweb_operating_unit/tests/test_report_qweb_operating_unit.py
  report_qweb_operating_unit/views/operating_unit_view.xml
  report_qweb_operating_unit/views/report_qweb_operating_unit.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#617 Syncing from upstream OCA/operating-unit (16.0)
  contract_operating_unit/i18n/it.po
Labels: 16.0

#618 Syncing from upstream OCA/operating-unit (17.0)
  report_qweb_operating_unit/i18n/it.po
Labels: 17.0

#619 18.0 mig operating unit
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/it.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/ir_rule.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/pyproject.toml
  operating_unit/readme/CONFIGURE.md
  operating_unit/readme/CONTRIBUTORS.md
  operating_unit/readme/DESCRIPTION.md
  operating_unit/readme/ROADMAP.md
  operating_unit/readme/USAGE.md
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/common.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
Labels: 18.0.t154504

#620 [18.0][MIG] operating_unit: Migration to 18.0
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/it.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/ir_rule.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/pyproject.toml
  operating_unit/readme/CONFIGURE.md
  operating_unit/readme/CONTRIBUTORS.md
  operating_unit/readme/DESCRIPTION.md
  operating_unit/readme/ROADMAP.md
  operating_unit/readme/USAGE.md
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/common.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
Labels: 18.0.project_sv_559

#621 [t154502][MIG] analytic_operating_unit: Migration to 18.0
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/i18n/es_AR.po
  analytic_operating_unit/i18n/es_MX.po
  analytic_operating_unit/i18n/it.po
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/pyproject.toml
  analytic_operating_unit/readme/CONTRIBUTORS.md
  analytic_operating_unit/readme/DESCRIPTION.md
  analytic_operating_unit/readme/USAGE.md
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/static/description/index.html
  analytic_operating_unit/static/src/components/analytic_distribution.esm.js
  analytic_operating_unit/views/analytic_account_view.xml
Labels: 18.0.t154502

#626 [t154502][MIG] analytic_operating_unit: Migration to 18.0
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/i18n/es_AR.po
  analytic_operating_unit/i18n/es_MX.po
  analytic_operating_unit/i18n/it.po
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/pyproject.toml
  analytic_operating_unit/readme/CONTRIBUTORS.md
  analytic_operating_unit/readme/DESCRIPTION.md
  analytic_operating_unit/readme/USAGE.md
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/static/description/index.html
  analytic_operating_unit/static/src/components/analytic_distribution.esm.js
  analytic_operating_unit/views/analytic_account_view.xml
Labels: 18.0.project_sv_559

#622 [t154505][MIG] stock_operating_unit: Migration to 18.0
  stock_operating_unit/README.rst
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/data/stock_data.xml
  stock_operating_unit/demo/stock_demo.xml
  stock_operating_unit/i18n/es_AR.po
  stock_operating_unit/i18n/it.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/model/__init__.py
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_move.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_quant.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/pyproject.toml
  stock_operating_unit/readme/CONFIGURE.md
  stock_operating_unit/readme/CONTRIBUTORS.md
  stock_operating_unit/readme/DESCRIPTION.md
  stock_operating_unit/readme/ROADMAP.md
  stock_operating_unit/readme/USAGE.md
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/index.html
  stock_operating_unit/tests/__init__.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
  stock_operating_unit/view/stock.xml
Labels: 18.0.t154505

#627 [t154505][MIG] stock_operating_unit: Migration to 18.0
  stock_operating_unit/README.rst
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/data/stock_data.xml
  stock_operating_unit/demo/stock_demo.xml
  stock_operating_unit/i18n/es_AR.po
  stock_operating_unit/i18n/it.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/model/__init__.py
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_move.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_quant.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/pyproject.toml
  stock_operating_unit/readme/CONFIGURE.md
  stock_operating_unit/readme/CONTRIBUTORS.md
  stock_operating_unit/readme/DESCRIPTION.md
  stock_operating_unit/readme/ROADMAP.md
  stock_operating_unit/readme/USAGE.md
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/index.html
  stock_operating_unit/tests/__init__.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
  stock_operating_unit/view/stock.xml
Labels: 18.0.project_sv_559

#625 [t154503][MIG] mrp_operating_unit: Migration to 18.0
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/pyproject.toml
  mrp_operating_unit/readme/CONTRIBUTORS.md
  mrp_operating_unit/readme/DESCRIPTION.md
  mrp_operating_unit/readme/USAGE.md
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
Labels: t154503

#624 [t154504][MIG] operating_unit: Migration to 18.0
  operating_unit/readme/CONTRIBUTORS.md
Labels: 18.0.project_sv_559

#628 [t154503][MIG] mrp_operating_unit: Migration to 18.0
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/pyproject.toml
  mrp_operating_unit/readme/CONTRIBUTORS.md
  mrp_operating_unit/readme/DESCRIPTION.md
  mrp_operating_unit/readme/USAGE.md
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
Labels: 18.0.project_sv_559

#629 Syncing from upstream OCA/operating-unit (14.0)
  account_asset_operating_unit/i18n/it.po
  contract_operating_unit/i18n/it.po
  contract_operating_unit_access_all/i18n/it.po
  crm_operating_unit/i18n/it.po
  hr_expense_operating_unit_access_all/i18n/it.po
  mail_template_operating_unit/i18n/it.po
  sales_team_operating_unit/i18n/it.po
Labels: 14.0

#630 Syncing from upstream OCA/operating-unit (14.0)
  account_financial_report_operating_unit/i18n/it.po
  hr_contract_operating_unit/i18n/it.po
  hr_expense_operating_unit/i18n/it.po
  hr_operating_unit/i18n/it.po
  hr_payroll_account_operating_unit/i18n/it.po
  mis_builder_budget_operating_unit/i18n/it.po
  mis_builder_operating_unit_access_all/i18n/it.po
  mrp_operating_unit/i18n/it.po
  product_operating_unit/i18n/it.po
  project_operating_unit/i18n/it.po
  purchase_request_operating_unit_access_all/i18n/it.po
  purchase_request_to_requisition_operating_unit/i18n/it.po
Labels: 14.0
