Repository brain-tec/operating-unit, pull requests merged in 2024-03, with the labels that each got.

#549 Syncing from upstream OCA/operating-unit (15.0)
  account_operating_unit/tests/test_payment_operating_unit.py
Labels: 15.0

#550 Update project branch with newer 16.0
  README.md
  analytic_operating_unit/i18n/it.po
  hr_operating_unit/README.rst
  hr_operating_unit/__init__.py
  hr_operating_unit/__manifest__.py
  hr_operating_unit/i18n/es.po
  hr_operating_unit/i18n/fr.po
  hr_operating_unit/i18n/hr_operating_unit.pot
  hr_operating_unit/i18n/it.po
  hr_operating_unit/models/__init__.py
  hr_operating_unit/models/hr_employee_base.py
  hr_operating_unit/models/hr_operating_unit.py
  hr_operating_unit/readme/CONTRIBUTORS.rst
  hr_operating_unit/readme/DESCRIPTION.rst
  hr_operating_unit/readme/USAGE.rst
  hr_operating_unit/security/security.xml
  hr_operating_unit/static/description/icon.png
  hr_operating_unit/static/description/index.html
  hr_operating_unit/views/hr_employee.xml
  product_operating_unit/i18n/it.po
  project_operating_unit/i18n/it.po
  sales_team_operating_unit/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/hr_operating_unit/odoo/addons/hr_operating_unit
  setup/hr_operating_unit/setup.py
  stock_operating_unit/i18n/it.po
Labels: 16.0.project_sa_690

#551 Syncing from upstream OCA/operating-unit (14.0)
  mis_builder_operating_unit/i18n/it.po
Labels: 14.0

#552 Syncing from upstream OCA/operating-unit (15.0)
  mis_builder_operating_unit/i18n/it.po
Labels: 15.0
