Repository brain-tec/operating-unit, pull requests merged in 2024-05, with the labels that each got.

#557 Syncing from upstream OCA/operating-unit (15.0)
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 15.0

#558 Syncing from upstream OCA/operating-unit (16.0)
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 16.0

#559 Syncing from upstream OCA/operating-unit (17.0)
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
Labels: 17.0

#560 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  hr_payroll_account_operating_unit/README.rst
  hr_payroll_account_operating_unit/__manifest__.py
  hr_payroll_account_operating_unit/models/hr_payslip.py
  hr_payroll_account_operating_unit/static/description/index.html
Labels: 15.0

#561 Update project branch with 16.0
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 16.0.project_sa_690

#562 Syncing from upstream OCA/operating-unit (13.0)
  README.md
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/i18n/da.po
  mis_builder_operating_unit/i18n/mis_builder_operating_unit.pot
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/static/description/index.html
  mis_builder_operating_unit/view/mis_builder.xml
Labels: 13.0

#563 Syncing from upstream OCA/operating-unit (15.0)
  purchase_request_operating_unit/test-requirements.txt
  stock_account_operating_unit/test-requirements.txt
Labels: 15.0

#564 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  purchase_operating_unit/README.rst
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/i18n/es.po
  purchase_operating_unit/i18n/it.po
  purchase_operating_unit/i18n/purchase_operating_unit.pot
  purchase_operating_unit/models/account_invoice.py
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/views/account_move_view.xml
Labels: 14.0

#565 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/i18n/es_MX.po
  account_operating_unit/models/account_move.py
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/wizards/__init__.py
  account_operating_unit/wizards/account_payment_register.py
Labels: 15.0

#566 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  purchase_operating_unit/README.rst
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/i18n/purchase_operating_unit.pot
  purchase_operating_unit/models/account_move.py
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/views/account_move_view.xml
Labels: 15.0

#567 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  purchase_operating_unit/README.rst
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/readme/CONTRIBUTORS.rst
  purchase_operating_unit/static/description/index.html
Labels: 14.0
