Repository brain-tec/operating-unit, pull requests merged in 2024-01, with the labels that each got.

#533 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  operating_unit/README.rst
  operating_unit/__manifest__.py
  operating_unit/models/res_users.py
  operating_unit/static/description/index.html
  operating_unit/tests/test_operating_unit.py
  product_operating_unit/README.rst
  product_operating_unit/__manifest__.py
  product_operating_unit/models/product_template.py
  product_operating_unit/static/description/index.html
Labels: 14.0

#534 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  operating_unit/README.rst
  operating_unit/__manifest__.py
  operating_unit/models/res_users.py
  operating_unit/static/description/index.html
  operating_unit/tests/test_operating_unit.py
Labels: 15.0

#535 Syncing from upstream OCA/operating-unit (16.0)
  README.md
  operating_unit/README.rst
  operating_unit/__manifest__.py
  operating_unit/models/res_users.py
  operating_unit/static/description/index.html
  operating_unit/tests/test_operating_unit.py
  product_operating_unit/README.rst
  product_operating_unit/__manifest__.py
  product_operating_unit/models/product_template.py
  product_operating_unit/static/description/index.html
Labels: 16.0

#536 Syncing from upstream OCA/operating-unit (14.0)
  account_asset_operating_unit/i18n/es.po
  account_operating_unit/i18n/es.po
  agreement_operating_unit/i18n/es.po
  crm_operating_unit/i18n/es.po
  hr_expense_operating_unit/i18n/es.po
  hr_operating_unit/i18n/es.po
  mis_builder_operating_unit/i18n/es.po
  mrp_operating_unit/i18n/es.po
  pos_operating_unit/i18n/es.po
  product_operating_unit/i18n/es.po
  project_operating_unit/i18n/es.po
  purchase_operating_unit/i18n/es.po
  purchase_requisition_operating_unit/i18n/es.po
  sale_stock_operating_unit/i18n/es.po
  stock_operating_unit/i18n/es.po
Labels: 14.0

#537 Update project branch
  README.md
  operating_unit/README.rst
  operating_unit/__manifest__.py
  operating_unit/models/res_users.py
  operating_unit/static/description/index.html
  operating_unit/tests/test_operating_unit.py
  product_operating_unit/README.rst
  product_operating_unit/__manifest__.py
  product_operating_unit/models/product_template.py
  product_operating_unit/static/description/index.html
Labels: 16.0.project_sa_690

#538 Syncing from upstream OCA/operating-unit (12.0)
  product_operating_unit/i18n/it.po
  purchase_operating_unit/i18n/it.po
  stock_operating_unit/i18n/it.po
Labels: 12.0

#539 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  purchase_operating_unit/README.rst
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/models/purchase_order.py
  purchase_operating_unit/static/description/index.html
  stock_operating_unit/i18n/it.po
Labels: 14.0

#540 Syncing from upstream OCA/operating-unit (15.0)
  mis_builder_operating_unit/i18n/it.po
Labels: 15.0

#541 Syncing from upstream OCA/operating-unit (16.0)
  analytic_operating_unit/i18n/it.po
  product_operating_unit/i18n/it.po
  project_operating_unit/i18n/it.po
  sales_team_operating_unit/i18n/it.po
  stock_operating_unit/i18n/it.po
Labels: 16.0

#542 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  contract_operating_unit/README.rst
  contract_operating_unit/__init__.py
  contract_operating_unit/__manifest__.py
  contract_operating_unit/i18n/contract_operating_unit.pot
  contract_operating_unit/models/__init__.py
  contract_operating_unit/models/contract.py
  contract_operating_unit/readme/CONTRIBUTORS.rst
  contract_operating_unit/readme/DESCRIPTION.rst
  contract_operating_unit/readme/USAGE.rst
  contract_operating_unit/security/contract_security.xml
  contract_operating_unit/static/description/icon.png
  contract_operating_unit/static/description/index.html
  contract_operating_unit/tests/__init__.py
  contract_operating_unit/tests/test_contract_operating_unit.py
  contract_operating_unit/views/contract_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/contract_operating_unit/odoo/addons/contract_operating_unit
  setup/contract_operating_unit/setup.py
Labels: 15.0

#543 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  purchase_request_operating_unit/README.rst
  purchase_request_operating_unit/__manifest__.py
  purchase_request_operating_unit/static/description/index.html
  purchase_request_operating_unit/wizard/purchase_request_line_make_purchase_order_view.xml
Labels: 15.0
