Repository brain-tec/operating-unit, pull requests merged in 2024-07, with the labels that each got.

#571 Syncing from upstream OCA/operating-unit (16.0)
  operating_unit/i18n/it.po
Labels: 16.0

#572 Update with latest 16.0
  operating_unit/i18n/it.po
Labels: 16.0.project_sa_690

#573 Syncing from upstream OCA/operating-unit (17.0)
  README.md
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/ir_rule.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/pyproject.toml
  operating_unit/readme/CONFIGURE.md
  operating_unit/readme/CONTRIBUTORS.md
  operating_unit/readme/DESCRIPTION.md
  operating_unit/readme/ROADMAP.md
  operating_unit/readme/USAGE.md
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/common.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#574 Syncing from upstream OCA/operating-unit (12.0)
  operating_unit/i18n/it.po
Labels: 12.0

#575 Syncing from upstream OCA/operating-unit (14.0)
  operating_unit/i18n/it.po
Labels: 14.0

#576 Syncing from upstream OCA/operating-unit (16.0)
  operating_unit/i18n/it.po
Labels: 16.0

#577 Syncing from upstream OCA/operating-unit (17.0)
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
Labels: 17.0

#578 Syncing from upstream OCA/operating-unit (17.0)
  operating_unit/i18n/it.po
Labels: 17.0

#579 Syncing from upstream OCA/operating-unit (12.0)
  operating_unit/i18n/it.po
Labels: 12.0

#580 Syncing from upstream OCA/operating-unit (14.0)
  operating_unit/i18n/it.po
Labels: 14.0

#581 Syncing from upstream OCA/operating-unit (16.0)
  operating_unit/i18n/it.po
Labels: 16.0

#582 Syncing from upstream OCA/operating-unit (17.0)
  README.md
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/i18n/es_AR.po
  analytic_operating_unit/i18n/es_MX.po
  analytic_operating_unit/i18n/it.po
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/pyproject.toml
  analytic_operating_unit/readme/CONTRIBUTORS.md
  analytic_operating_unit/readme/DESCRIPTION.md
  analytic_operating_unit/readme/USAGE.md
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/static/description/index.html
  analytic_operating_unit/static/src/components/analytic_distribution.esm.js
  analytic_operating_unit/views/analytic_account_view.xml
  operating_unit/i18n/it.po
  sales_team_operating_unit/README.rst
  sales_team_operating_unit/__init__.py
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/i18n/es_AR.po
  sales_team_operating_unit/i18n/es_MX.po
  sales_team_operating_unit/i18n/it.po
  sales_team_operating_unit/i18n/sales_team_operating_unit.pot
  sales_team_operating_unit/models/__init__.py
  sales_team_operating_unit/models/crm_team.py
  sales_team_operating_unit/pyproject.toml
  sales_team_operating_unit/readme/CONTRIBUTORS.md
  sales_team_operating_unit/readme/DESCRIPTION.md
  sales_team_operating_unit/readme/USAGE.md
  sales_team_operating_unit/security/crm_security.xml
  sales_team_operating_unit/static/description/icon.png
  sales_team_operating_unit/static/description/index.html
  sales_team_operating_unit/tests/__init__.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  sales_team_operating_unit/views/crm_team_view.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#583 Update project branch with latest 16.0
  operating_unit/i18n/it.po
Labels: 16.0.project_sa_690

#585 Syncing from upstream OCA/operating-unit (17.0)
  res_partner_operating_unit/i18n/it.po
Labels: 17.0

#586 Syncing from upstream OCA/operating-unit (16.0)
  operating_unit/i18n/es_AR.po
Labels: 16.0
