Repository brain-tec/operating-unit, pull requests merged in 2025-03, with the labels that each got.

#667 Syncing from upstream OCA/operating-unit (18.0)
  README.md
  setup/_metapackage/pyproject.toml
  stock_operating_unit_access_all/README.rst
  stock_operating_unit_access_all/__init__.py
  stock_operating_unit_access_all/__manifest__.py
  stock_operating_unit_access_all/i18n/it.po
  stock_operating_unit_access_all/i18n/stock_operating_unit_access_all.pot
  stock_operating_unit_access_all/pyproject.toml
  stock_operating_unit_access_all/readme/CONFIGURE.md
  stock_operating_unit_access_all/readme/CONTRIBUTORS.md
  stock_operating_unit_access_all/readme/DESCRIPTION.md
  stock_operating_unit_access_all/security/stock_security.xml
  stock_operating_unit_access_all/static/description/icon.png
  stock_operating_unit_access_all/static/description/index.html
Labels: 18.0

#668 Syncing from upstream OCA/operating-unit (17.0)
  README.md
  contract_operating_unit/README.rst
  contract_operating_unit/__manifest__.py
  contract_operating_unit/security/contract_security.xml
  contract_operating_unit/static/description/index.html
Labels: 17.0

#672 [18.0][MIG] mrp_operating_unit: Migration to 18.0
  mrp_operating_unit/models/mrp.py
Labels: 18.0.project_sv_559

#673 Syncing from upstream OCA/operating-unit (18.0)
  README.md
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/i18n/es_AR.po
  analytic_operating_unit/i18n/es_MX.po
  analytic_operating_unit/i18n/it.po
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/pyproject.toml
  analytic_operating_unit/readme/CONTRIBUTORS.md
  analytic_operating_unit/readme/DESCRIPTION.md
  analytic_operating_unit/readme/USAGE.md
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/static/description/index.html
  analytic_operating_unit/static/src/components/analytic_distribution.esm.js
  analytic_operating_unit/views/analytic_account_view.xml
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/pyproject.toml
  mrp_operating_unit/readme/CONTRIBUTORS.md
  mrp_operating_unit/readme/DESCRIPTION.md
  mrp_operating_unit/readme/USAGE.md
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#674 Syncing from upstream OCA/operating-unit (14.0)
  crm_operating_unit/i18n/it.po
  hr_contract_operating_unit/i18n/it.po
  hr_payroll_account_operating_unit/i18n/it.po
  mail_template_operating_unit/i18n/it.po
  mis_builder_budget_operating_unit/i18n/it.po
  mrp_operating_unit/i18n/it.po
  product_operating_unit/i18n/it.po
  project_operating_unit/i18n/it.po
Labels: 14.0

#675 Syncing from upstream OCA/operating-unit (16.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/i18n/de.po
  account_operating_unit/i18n/es_MX.po
  account_operating_unit/i18n/it.po
  account_operating_unit/migrations/16.0.1.1.0/pre-migration.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_move_line.py
  account_operating_unit/static/description/index.html
  account_operating_unit/views/account_move_view.xml
Labels: 16.0

#676 Syncing from upstream OCA/operating-unit (17.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/i18n/es_MX.po
  account_operating_unit/i18n/it.po
  account_operating_unit/migrations/17.0.1.1.0/pre-migration.py
  account_operating_unit/models/account_move.py
  account_operating_unit/static/description/index.html
  account_operating_unit/views/account_move_view.xml
Labels: 17.0

#677 Syncing from upstream OCA/operating-unit (16.0)
  account_operating_unit/i18n/de.po
  project_operating_unit/i18n/de.po
  report_qweb_operating_unit/i18n/de.po
Labels: 16.0

#678 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__manifest__.py
  account_operating_unit/models/account_move.py
  account_operating_unit/static/description/index.html
Labels: 15.0

#680 Syncing from upstream OCA/operating-unit (17.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/it.po
  account_operating_unit/models/account_move.py
  account_operating_unit/static/description/index.html
Labels: 17.0

#681 Syncing from upstream OCA/operating-unit (18.0)
  mrp_operating_unit/i18n/it.po
Labels: 18.0

#682 Syncing from upstream OCA/operating-unit (16.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__manifest__.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_move_line.py
  account_operating_unit/static/description/index.html
Labels: 16.0

#683 Syncing from upstream OCA/operating-unit (17.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__manifest__.py
  account_operating_unit/models/account_move.py
  account_operating_unit/static/description/index.html
Labels: 17.0
