Repository brain-tec/operating-unit, pull requests merged in 2025-02, with the labels that each got.

#643 Syncing from upstream OCA/operating-unit (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .oca_hooks.cfg
  .pre-commit-config.yaml
Labels: 13.0

#644 Syncing from upstream OCA/operating-unit (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 14.0

#645 Syncing from upstream OCA/operating-unit (15.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 15.0

#646 Syncing from upstream OCA/operating-unit (16.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 16.0

#647 Syncing from upstream OCA/operating-unit (17.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .ruff.toml
Labels: 17.0

#648 Syncing from upstream OCA/operating-unit (18.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .ruff.toml
  checklog-odoo.cfg
Labels: 18.0

#649 [t154870] Fixed double entry by removing OCA code
  stock_account_operating_unit/model/stock_move.py
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
Labels: 17.0.project_mg_732

#650 Syncing from upstream OCA/operating-unit (15.0)
  account_operating_unit/i18n/es.po
  operating_unit/i18n/es.po
Labels: 15.0

#651 Syncing from upstream OCA/operating-unit (15.0)
  analytic_operating_unit/i18n/es.po
  stock_operating_unit/i18n/es.po
Labels: 15.0

#652 Syncing from upstream OCA/operating-unit (17.0)
  README.md
  operating_unit/README.rst
  operating_unit/__manifest__.py
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/it.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/index.html
  operating_unit/tests/common.py
Labels: 17.0

#653 Syncing from upstream OCA/operating-unit (18.0)
  README.md
  setup/_metapackage/pyproject.toml
  stock_operating_unit/README.rst
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/data/stock_data.xml
  stock_operating_unit/demo/stock_demo.xml
  stock_operating_unit/i18n/es_AR.po
  stock_operating_unit/i18n/it.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/model/__init__.py
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_move.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_quant.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/pyproject.toml
  stock_operating_unit/readme/CONFIGURE.md
  stock_operating_unit/readme/CONTRIBUTORS.md
  stock_operating_unit/readme/DESCRIPTION.md
  stock_operating_unit/readme/ROADMAP.md
  stock_operating_unit/readme/USAGE.md
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/index.html
  stock_operating_unit/tests/__init__.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
  stock_operating_unit/view/stock.xml
Labels: 18.0

#654 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  stock_operating_unit/README.rst
  stock_operating_unit/__manifest__.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/static/description/index.html
Labels: 14.0

#655 Syncing from upstream OCA/operating-unit (15.0)
  account_financial_report_operating_unit/i18n/es.po
  operating_unit_access_all/i18n/es.po
  purchase_operating_unit/i18n/es.po
  purchase_request_operating_unit/i18n/es.po
  purchase_requisition_operating_unit/i18n/es.po
  sale_operating_unit/i18n/es.po
Labels: 15.0

#657 Syncing from upstream OCA/operating-unit (15.0)
  account_operating_unit_access_all/i18n/es.po
  purchase_request_operating_unit_access_all/i18n/es.po
Labels: 15.0

#658 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  purchase_operating_unit_access_all/i18n/es.po
  sales_team_operating_unit/i18n/es.po
  stock_operating_unit/README.rst
  stock_operating_unit/__manifest__.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/static/description/index.html
Labels: 15.0

#659 Syncing from upstream OCA/operating-unit (16.0)
  README.md
  stock_operating_unit/README.rst
  stock_operating_unit/__manifest__.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/static/description/index.html
Labels: 16.0

#660 Syncing from upstream OCA/operating-unit (17.0)
  README.md
  stock_operating_unit/README.rst
  stock_operating_unit/__manifest__.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/static/description/index.html
Labels: 17.0

#661 Syncing from upstream OCA/operating-unit (15.0)
  operating_unit/i18n/es.po
Labels: 15.0

#662 Syncing from upstream OCA/operating-unit (17.0)
  operating_unit/i18n/es.po
Labels: 17.0

#663 Syncing from upstream OCA/operating-unit (15.0)
  account_financial_report_operating_unit/README.rst
  account_financial_report_operating_unit/__manifest__.py
  account_financial_report_operating_unit/static/description/index.html
Labels: 15.0

#665 Syncing from upstream OCA/operating-unit (17.0)
  account_financial_report_operating_unit/README.rst
  account_financial_report_operating_unit/__manifest__.py
  account_financial_report_operating_unit/static/description/index.html
Labels: 17.0

#666 Syncing from upstream OCA/operating-unit (15.0)
  README.md
  account_financial_report_operating_unit/README.rst
  account_financial_report_operating_unit/__manifest__.py
  account_financial_report_operating_unit/i18n/account_financial_report_operating_unit.pot
  account_financial_report_operating_unit/i18n/es.po
  account_financial_report_operating_unit/static/description/index.html
  account_financial_report_operating_unit/wizards/__init__.py
  account_financial_report_operating_unit/wizards/abstract_wizard.py
  account_financial_report_operating_unit/wizards/aged_partner_balance_wizard.py
  account_financial_report_operating_unit/wizards/general_ledger_wizard.py
  account_financial_report_operating_unit/wizards/journal_ledger_wizard.py
  account_financial_report_operating_unit/wizards/journal_ledger_wizard_view.xml
  account_financial_report_operating_unit/wizards/open_items_wizard.py
  account_financial_report_operating_unit/wizards/trial_balance_wizard.py
Labels: 15.0
