Repository brain-tec/operating-unit, pull requests merged in 2025-01, with the labels that each got.

#631 Syncing from upstream OCA/operating-unit (14.0)
  purchase_request_operating_unit/i18n/it.po
  sale_crm_operating_unit/i18n/it.po
Labels: 14.0

#632 Syncing from upstream OCA/operating-unit (14.0)
  account_asset_operating_unit_access_all/i18n/it.po
  account_operating_unit_access_all/i18n/it.po
  agreement_operating_unit/i18n/it.po
  fieldservice_operating_unit/i18n/it.po
  purchase_requisition_operating_unit/i18n/it.po
  report_qweb_operating_unit/i18n/it.po
  sale_template_operating_unit/i18n/it.po
Labels: 14.0

#633 Syncing from upstream OCA/operating-unit (18.0)
  README.md
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/it.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/ir_rule.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/pyproject.toml
  operating_unit/readme/CONFIGURE.md
  operating_unit/readme/CONTRIBUTORS.md
  operating_unit/readme/DESCRIPTION.md
  operating_unit/readme/ROADMAP.md
  operating_unit/readme/USAGE.md
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/common.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#634 [MIG] stock_account_operating_unit: Migration to 17.0
  stock_account_operating_unit/README.rst
  stock_account_operating_unit/__init__.py
  stock_account_operating_unit/__manifest__.py
  stock_account_operating_unit/i18n/es.po
  stock_account_operating_unit/i18n/stock_account_operating_unit.pot
  stock_account_operating_unit/model/__init__.py
  stock_account_operating_unit/model/stock_move.py
  stock_account_operating_unit/pyproject.toml
  stock_account_operating_unit/readme/CONFIGURATION.rst
  stock_account_operating_unit/readme/CONTRIBUTORS.md
  stock_account_operating_unit/readme/DESCRIPTION.md
  stock_account_operating_unit/readme/USAGE.md
  stock_account_operating_unit/static/description/icon.png
  stock_account_operating_unit/static/description/index.html
  stock_account_operating_unit/tests/__init__.py
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
Labels: 17.0.project_mg_732

#635 [t154870] Fix Operating Unit Missing on Journal Entry on Inventory Ad…
  stock_account_operating_unit/model/stock_move.py
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
Labels: 17.0.project_mg_732

#636 [t154870] Fix Operating Unit Missing on Journal Entry on Inventory Adjustment
  stock_account_operating_unit/tests/test_stock_account_operating_unit.py
Labels: 17.0.project_mg_732

#637 Syncing from upstream OCA/operating-unit (16.0)
  report_qweb_operating_unit/i18n/it.po
Labels: 16.0

#638 [17.0][IMP] Added operating units group filter for PoS Orders Report
  pos_operating_unit/README.rst
  pos_operating_unit/__init__.py
  pos_operating_unit/__manifest__.py
  pos_operating_unit/readme/CONTRIBUTORS.md
  pos_operating_unit/report/__init__.py
  pos_operating_unit/report/pos_order_report.py
  pos_operating_unit/static/description/index.html
  pos_operating_unit/views/pos_order_report_view.xml
Labels: 17.0.project_mg_732

#639 Syncing from upstream OCA/operating-unit (14.0)
  mis_builder_operating_unit/i18n/it.po
  mis_builder_operating_unit_access_all/i18n/it.po
  purchase_operating_unit/i18n/it.po
  purchase_request_operating_unit_access_all/i18n/it.po
Labels: 14.0

#642 Syncing from upstream OCA/operating-unit (14.0)
  README.md
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/i18n/es.po
  account_operating_unit/i18n/it.po
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_payment.py
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/wizards/__init__.py
  account_operating_unit/wizards/account_payment_register.py
Labels: 14.0
